###
GET http://127.0.0.1:9090/api/goods/1


###
POST http://127.0.0.1:9090/api/goods
Content-Type: application/json

{
  "name": "content",
  "price": 5
}

###
GET http://127.0.0.1:9090/api/goods_list

