"""empty message

Revision ID: 029e486a6732
Revises: fb7a520af96a
Create Date: 2021-03-15 23:24:18.558926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '029e486a6732'
down_revision = 'fb7a520af96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_target_t_content', table_name='target_t')
    op.drop_column('target_t', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_t', sa.Column('content', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_target_t_content', 'target_t', ['content'], unique=False)
    # ### end Alembic commands ###
