"""empty message

Revision ID: 02b6dc0d677f
Revises: 90bbc7ced402
Create Date: 2021-03-30 23:53:27.991098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b6dc0d677f'
down_revision = '90bbc7ced402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_user_t', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('video_user_t', sa.Column('resume', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_user_t', 'resume')
    op.drop_column('video_user_t', 'brand')
    # ### end Alembic commands ###
