"""empty message

Revision ID: 04a05ecff956
Revises: b944dbdbc635
Create Date: 2021-05-29 20:10:05.983158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04a05ecff956'
down_revision = 'b944dbdbc635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'video_user_t', ['username'])
    op.drop_column('video_user_t', 'outer_chain')
    op.drop_column('works_t', 'outer_chain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_t', sa.Column('outer_chain', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('video_user_t', sa.Column('outer_chain', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'video_user_t', type_='unique')
    # ### end Alembic commands ###
