"""empty message

Revision ID: 0699f53da806
Revises: a51761b28989
Create Date: 2020-08-07 19:10:23.753297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0699f53da806'
down_revision = 'a51761b28989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_t', sa.Column('belong', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_t', 'belong')
    # ### end Alembic commands ###
