"""empty message

Revision ID: 0887a8251cb6
Revises: 8ee170e031d3
Create Date: 2022-02-23 18:40:34.044826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0887a8251cb6'
down_revision = '8ee170e031d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('price', sa.Float(precision='14,2'), nullable=True, comment='价格(每个)'))
    op.drop_column('order_t', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('total_price', mysql.FLOAT(precision=14, scale=2), nullable=True, comment='价格(每个)'))
    op.drop_column('order_t', 'price')
    # ### end Alembic commands ###
