"""empty message

Revision ID: 0a5ded26fcdd
Revises: 9abe1f5299ed
Create Date: 2021-03-15 23:25:24.090517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5ded26fcdd'
down_revision = '9abe1f5299ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_t', sa.Column('price', sa.Float(), nullable=True))
    op.drop_index('ix_target_t_content', table_name='target_t')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_target_t_content', 'target_t', ['content'], unique=False)
    op.drop_column('target_t', 'price')
    # ### end Alembic commands ###
