"""empty message

Revision ID: 0b7146a1a3f8
Revises: 5f5782abbd3d
Create Date: 2022-05-20 23:57:36.860491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b7146a1a3f8'
down_revision = '5f5782abbd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('announcement', 'title',
               existing_type=mysql.VARCHAR(length=128),
               comment='标题',
               existing_nullable=True)
    op.alter_column('announcement', 'content',
               existing_type=mysql.VARCHAR(length=150),
               comment='内容',
               existing_nullable=True)
    op.alter_column('announcement', 'images',
               existing_type=mysql.VARCHAR(length=70),
               comment='配图path',
               existing_nullable=True)
    op.alter_column('goods_t', 'name',
               existing_type=mysql.VARCHAR(length=256),
               comment='商品名',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'code',
               existing_type=mysql.VARCHAR(length=255),
               comment='邀请码',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'invitation_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='邀请id',
               existing_nullable=True)
    op.alter_column('log_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('log_t', 'message',
               existing_type=mysql.TEXT(),
               comment='消息',
               existing_nullable=True)
    op.alter_column('log_t', 'tag',
               existing_type=mysql.TEXT(),
               comment='标签',
               existing_nullable=True)
    op.alter_column('log_t', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否消费',
               existing_nullable=True)
    op.alter_column('order_t', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='店铺id',
               existing_nullable=True)
    op.alter_column('order_t', 'goods_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品id',
               existing_nullable=True)
    op.alter_column('order_t', 'goods_img',
               existing_type=mysql.VARCHAR(length=256),
               comment='商品图片path',
               existing_nullable=True)
    op.alter_column('order_t', 'goods_name',
               existing_type=mysql.VARCHAR(length=256),
               comment='商品名',
               existing_nullable=True)
    op.alter_column('order_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('order_t', 'num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='数量',
               existing_nullable=True)
    op.alter_column('prove_vo', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='父级id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'value',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='内容',
               existing_nullable=True)
    op.alter_column('prove_vo', 'sort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='排序顺序',
               existing_nullable=True)
    op.alter_column('prove_vo', 'wight',
               existing_type=mysql.INTEGER(display_width=11),
               comment='权重',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'role',
               existing_type=mysql.VARCHAR(length=128),
               comment='角色',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'permission',
               existing_type=mysql.VARCHAR(length=128),
               comment='权限',
               existing_nullable=True)
    op.alter_column('store_member_t', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='店铺id',
               existing_nullable=True)
    op.alter_column('store_member_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('store_t', 'name',
               existing_type=mysql.VARCHAR(length=256),
               comment='姓名',
               existing_nullable=True)
    op.alter_column('store_t', 'store_name',
               existing_type=mysql.INTEGER(display_width=11),
               comment='店铺名',
               existing_nullable=True)
    op.alter_column('store_t', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('store_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('store_t', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码hash',
               existing_nullable=False)
    op.alter_column('story_vo', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('story_vo', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='父级id',
               existing_nullable=True)
    op.alter_column('story_vo', 'value',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='内容',
               existing_nullable=True)
    op.alter_column('story_vo', 'sort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='排序顺序',
               existing_nullable=True)
    op.alter_column('story_vo', 'wight',
               existing_type=mysql.INTEGER(display_width=11),
               comment='权重',
               existing_nullable=True)
    op.alter_column('suggest_t', 'content',
               existing_type=mysql.VARCHAR(length=150),
               comment='内容',
               existing_nullable=True)
    op.alter_column('suggest_t', 'image',
               existing_type=mysql.VARCHAR(length=70),
               comment='配图path',
               existing_nullable=True)
    op.alter_column('suggest_t', 'announcement_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='反馈的公告id',
               existing_nullable=True)
    op.alter_column('target_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户 id',
               existing_nullable=True)
    op.alter_column('target_t', 'title',
               existing_type=mysql.VARCHAR(length=255),
               comment='标题',
               existing_nullable=True)
    op.alter_column('target_t', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=1000),
               comment='内容',
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='头像path',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=60),
               comment='email',
               existing_nullable=True)
    op.alter_column('user', 'userType',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户类型',
               existing_nullable=True)
    op.alter_column('user', 'describe',
               existing_type=mysql.VARCHAR(length=255),
               comment='签名',
               existing_nullable=True)
    op.alter_column('user', 'id_card',
               existing_type=mysql.VARCHAR(length=255),
               comment='身份证',
               existing_nullable=True)
    op.alter_column('user', 'tiktok_number',
               existing_type=mysql.VARCHAR(length=255),
               comment='抖音号',
               existing_nullable=True)
    op.alter_column('user', 'video_number',
               existing_type=mysql.VARCHAR(length=255),
               comment='视频号',
               existing_nullable=True)
    op.alter_column('user', 'wechat_number',
               existing_type=mysql.VARCHAR(length=255),
               comment='微信号',
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=255),
               comment='角色',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码hash',
               existing_nullable=False)
    op.alter_column('user_role_t', 'user_id',
               existing_type=mysql.VARCHAR(length=128),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('user_role_t', 'role',
               existing_type=mysql.VARCHAR(length=128),
               comment='角色',
               existing_nullable=True)
    op.alter_column('wallet_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='店铺id',
               existing_nullable=True)
    op.alter_column('worker_t', 'belong',
               existing_type=mysql.INTEGER(display_width=11),
               comment='所属id',
               existing_nullable=True)
    op.alter_column('worker_t', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='姓名',
               existing_nullable=True)
    op.alter_column('worker_t', 'birthday',
               existing_type=sa.DATE(),
               comment='出生日期',
               existing_nullable=True)
    op.alter_column('worker_t', 'id_card_number',
               existing_type=mysql.VARCHAR(length=255),
               comment='身份证id',
               existing_nullable=True)
    op.alter_column('worker_t', 'start_time',
               existing_type=sa.DATE(),
               comment='入职日期',
               existing_nullable=True)
    op.alter_column('worker_t', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'date',
               existing_type=sa.DATE(),
               comment='日期',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'worker_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='工人id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning_area',
               existing_type=mysql.VARCHAR(length=255),
               comment='上午工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning_content',
               existing_type=mysql.VARCHAR(length=255),
               comment='上午工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon_area',
               existing_type=mysql.VARCHAR(length=255),
               comment='中午工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon_content',
               existing_type=mysql.VARCHAR(length=255),
               comment='中午工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon_area',
               existing_type=mysql.VARCHAR(length=255),
               comment='下午工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon_content',
               existing_type=mysql.VARCHAR(length=255),
               comment='下午工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'night_area',
               existing_type=mysql.VARCHAR(length=255),
               comment='晚上工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'night_content',
               existing_type=mysql.VARCHAR(length=255),
               comment='晚上工作内容',
               existing_nullable=True)
    op.alter_column('works_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_nullable=True)
    op.alter_column('works_t', 'describe',
               existing_type=mysql.VARCHAR(length=255),
               comment='描述介绍',
               existing_nullable=True)
    op.alter_column('works_t', 'file',
               existing_type=mysql.VARCHAR(length=255),
               comment='视频path',
               existing_nullable=True)
    op.alter_column('works_t', 'start',
               existing_type=mysql.INTEGER(display_width=11),
               comment='点赞数',
               existing_nullable=True)
    op.alter_column('works_t', 'thumbnail',
               existing_type=mysql.VARCHAR(length=128),
               comment='封面图片path',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'thumbnail',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='封面图片path',
               existing_nullable=True)
    op.alter_column('works_t', 'start',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='点赞数',
               existing_nullable=True)
    op.alter_column('works_t', 'file',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='视频path',
               existing_nullable=True)
    op.alter_column('works_t', 'describe',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='描述介绍',
               existing_nullable=True)
    op.alter_column('works_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'night_content',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='晚上工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'night_area',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='晚上工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon_content',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='下午工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon_area',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='下午工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon_content',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='中午工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon_area',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='中午工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning_content',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='上午工作内容',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning_area',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='上午工作地点',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'worker_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='工人id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='日期',
               existing_nullable=True)
    op.alter_column('worker_t', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('worker_t', 'start_time',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='入职日期',
               existing_nullable=True)
    op.alter_column('worker_t', 'id_card_number',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='身份证id',
               existing_nullable=True)
    op.alter_column('worker_t', 'birthday',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='出生日期',
               existing_nullable=True)
    op.alter_column('worker_t', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='姓名',
               existing_nullable=True)
    op.alter_column('worker_t', 'belong',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='所属id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='店铺id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('user_role_t', 'role',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='角色',
               existing_nullable=True)
    op.alter_column('user_role_t', 'user_id',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码hash',
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='角色',
               existing_nullable=True)
    op.alter_column('user', 'wechat_number',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='微信号',
               existing_nullable=True)
    op.alter_column('user', 'video_number',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='视频号',
               existing_nullable=True)
    op.alter_column('user', 'tiktok_number',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='抖音号',
               existing_nullable=True)
    op.alter_column('user', 'id_card',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='身份证',
               existing_nullable=True)
    op.alter_column('user', 'describe',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='签名',
               existing_nullable=True)
    op.alter_column('user', 'userType',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户类型',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=60),
               comment=None,
               existing_comment='email',
               existing_nullable=True)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment=None,
               existing_comment='头像path',
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('target_t', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=1000),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('target_t', 'title',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='标题',
               existing_nullable=True)
    op.alter_column('target_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户 id',
               existing_nullable=True)
    op.alter_column('suggest_t', 'announcement_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='反馈的公告id',
               existing_nullable=True)
    op.alter_column('suggest_t', 'image',
               existing_type=mysql.VARCHAR(length=70),
               comment=None,
               existing_comment='配图path',
               existing_nullable=True)
    op.alter_column('suggest_t', 'content',
               existing_type=mysql.VARCHAR(length=150),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('story_vo', 'wight',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='权重',
               existing_nullable=True)
    op.alter_column('story_vo', 'sort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=True)
    op.alter_column('story_vo', 'value',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('story_vo', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='父级id',
               existing_nullable=True)
    op.alter_column('story_vo', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('store_t', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码hash',
               existing_nullable=False)
    op.alter_column('store_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('store_t', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('store_t', 'store_name',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='店铺名',
               existing_nullable=True)
    op.alter_column('store_t', 'name',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='姓名',
               existing_nullable=True)
    op.alter_column('store_member_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('store_member_t', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='店铺id',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'permission',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='权限',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'role',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='角色',
               existing_nullable=True)
    op.alter_column('prove_vo', 'wight',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='权重',
               existing_nullable=True)
    op.alter_column('prove_vo', 'sort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=True)
    op.alter_column('prove_vo', 'value',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('prove_vo', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='父级id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('order_t', 'num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='数量',
               existing_nullable=True)
    op.alter_column('order_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('order_t', 'goods_name',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='商品名',
               existing_nullable=True)
    op.alter_column('order_t', 'goods_img',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='商品图片path',
               existing_nullable=True)
    op.alter_column('order_t', 'goods_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='商品id',
               existing_nullable=True)
    op.alter_column('order_t', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='店铺id',
               existing_nullable=True)
    op.alter_column('log_t', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否消费',
               existing_nullable=True)
    op.alter_column('log_t', 'tag',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='标签',
               existing_nullable=True)
    op.alter_column('log_t', 'message',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='消息',
               existing_nullable=True)
    op.alter_column('log_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'invitation_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='邀请id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='邀请码',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    op.alter_column('goods_t', 'name',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='商品名',
               existing_nullable=True)
    op.alter_column('announcement', 'images',
               existing_type=mysql.VARCHAR(length=70),
               comment=None,
               existing_comment='配图path',
               existing_nullable=True)
    op.alter_column('announcement', 'content',
               existing_type=mysql.VARCHAR(length=150),
               comment=None,
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('announcement', 'title',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='标题',
               existing_nullable=True)
    op.alter_column('announcement', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
    # ### end Alembic commands ###
