"""empty message

Revision ID: 0eccd3d73d80
Revises: 9563e9cd6f13
Create Date: 2022-02-09 15:32:02.039675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0eccd3d73d80'
down_revision = '9563e9cd6f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_t', 'sex',
               existing_type=mysql.ENUM('男', '女', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='枚举值: MALE:男性; FEMALE:女性;',
               existing_nullable=True)
    op.add_column('works_t', sa.Column('state2', sa.Enum('APPROVE', 'NOT_APPROVE', 'NONE', 'NEXT', name='reviewenum'), nullable=True, comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works_t', 'state2')
    op.alter_column('worker_t', 'sex',
               existing_type=mysql.ENUM('男', '女', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment=None,
               existing_comment='枚举值: MALE:男性; FEMALE:女性;',
               existing_nullable=True)
    # ### end Alembic commands ###
