"""empty message

Revision ID: 103365ae7e69
Revises: 9612144f06da
Create Date: 2022-02-09 14:28:25.652195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '103365ae7e69'
down_revision = '9612144f06da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_t', sa.Column('state', sa.Enum('APPROVE', 'NOT_APPROVE', 'NONE'), nullable=True))
    op.alter_column('user_cloud_space', 'file_name',
               existing_type=mysql.VARCHAR(length=150),
               comment='文件原始名称',
               existing_comment='xxx.txt',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'file_path',
               existing_type=mysql.VARCHAR(length=150),
               comment='文件路径',
               existing_comment='/xxx/xxx.txt',
               existing_nullable=True)
    op.add_column('works_t', sa.Column('state', sa.Enum('APPROVE', 'NOT_APPROVE', 'NONE'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works_t', 'state')
    op.alter_column('user_cloud_space', 'file_path',
               existing_type=mysql.VARCHAR(length=150),
               comment='/xxx/xxx.txt',
               existing_comment='文件路径',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'file_name',
               existing_type=mysql.VARCHAR(length=150),
               comment='xxx.txt',
               existing_comment='文件原始名称',
               existing_nullable=True)
    op.drop_column('target_t', 'state')
    # ### end Alembic commands ###
