"""empty message

Revision ID: 104e0d54c746
Revises: 5916edd3f577
Create Date: 2021-03-14 21:49:52.427541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104e0d54c746'
down_revision = '5916edd3f577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_user_t', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_user_t', 'username')
    # ### end Alembic commands ###
