"""empty message

Revision ID: 1a25fbfe1fc5
Revises: b1d695e100e0
Create Date: 2020-11-09 00:34:09.138929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a25fbfe1fc5'
down_revision = 'b1d695e100e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_time_t2',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('morning_start', sa.Time(), nullable=True),
    sa.Column('morning_end', sa.Time(), nullable=True),
    sa.Column('noon_start', sa.Time(), nullable=True),
    sa.Column('noon_end', sa.Time(), nullable=True),
    sa.Column('afternoon_start', sa.Time(), nullable=True),
    sa.Column('afternoon_end', sa.Time(), nullable=True),
    sa.Column('evening_start', sa.Time(), nullable=True),
    sa.Column('evening_end', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.Column('json_data2', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=255), server_default='123', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_time_t2')
    # ### end Alembic commands ###
