"""empty message

Revision ID: 1a77ad89c80c
Revises: c2a27123aece
Create Date: 2020-07-12 02:43:33.602380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a77ad89c80c'
down_revision = 'c2a27123aece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_t', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('wallet_t', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_t', sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('wallet_t', 'user_id')
    # ### end Alembic commands ###
