"""empty message

Revision ID: 2128bc702a7d
Revises: bd1aba265fe1
Create Date: 2020-09-13 21:08:59.197408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2128bc702a7d'
down_revision = 'bd1aba265fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'worker_time_t', ['worker_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_time_t', type_='unique')
    # ### end Alembic commands ###
