"""empty message

Revision ID: 221d671aef92
Revises: 6c3f133aa575
Create Date: 2020-08-03 23:46:48.620332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221d671aef92'
down_revision = '6c3f133aa575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_member_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_member_t_store_id'), 'store_member_t', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_member_t_user_id'), 'store_member_t', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_member_t_user_id'), table_name='store_member_t')
    op.drop_index(op.f('ix_store_member_t_store_id'), table_name='store_member_t')
    op.drop_table('store_member_t')
    # ### end Alembic commands ###
