"""empty message

Revision ID: 26aa3ae4bf83
Revises: 8a48fedf8d3b
Create Date: 2021-02-03 23:38:26.576935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aa3ae4bf83'
down_revision = '8a48fedf8d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
