"""empty message

Revision ID: 27b9d3ee5c4c
Revises: 4e55e8b7230e
Create Date: 2021-04-10 12:53:52.591433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b9d3ee5c4c'
down_revision = '4e55e8b7230e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_t', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works_t', 'thumbnail')
    # ### end Alembic commands ###
