"""empty message

Revision ID: 2ee0be6df2da
Revises: 30cf17311fa3
Create Date: 2022-02-20 13:28:41.773404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee0be6df2da'
down_revision = '30cf17311fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_member_t', sa.Column('user_type', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_store_member_t_user_type'), 'store_member_t', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_member_t_user_type'), table_name='store_member_t')
    op.drop_column('store_member_t', 'user_type')
    # ### end Alembic commands ###
