"""empty message

Revision ID: 30cf17311fa3
Revises: a1cd703ec517
Create Date: 2022-02-18 19:26:18.109523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30cf17311fa3'
down_revision = 'a1cd703ec517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.Enum('APPROVE', 'NOT_APPROVE', 'NONE', 'NEXT', name='reviewenum'),
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state',
               existing_type=sa.Enum('APPROVE', 'NOT_APPROVE', 'NONE', 'NEXT', name='reviewenum'),
               type_=mysql.VARCHAR(length=128),
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    # ### end Alembic commands ###
