"""empty message

Revision ID: 333235dc4298
Revises: 53ce361ab89a
Create Date: 2021-02-21 17:00:15.971338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333235dc4298'
down_revision = '53ce361ab89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['goods_t.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_t_goods_id'), 'order_t', ['goods_id'], unique=False)
    op.create_index(op.f('ix_order_t_user_id'), 'order_t', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_t_user_id'), table_name='order_t')
    op.drop_index(op.f('ix_order_t_goods_id'), table_name='order_t')
    op.drop_table('order_t')
    # ### end Alembic commands ###
