"""empty message

Revision ID: 46766e23a8f6
Revises: 7a68e1d1dd73
Create Date: 2023-09-18 11:09:08.065057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46766e23a8f6'
down_revision = '7a68e1d1dd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'))
    op.create_index(op.f('ix_order_t_user_id'), 'order_t', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_t_user_id'), table_name='order_t')
    op.drop_column('order_t', 'user_id')
    # ### end Alembic commands ###
