"""empty message

Revision ID: 4ca64e311ab7
Revises: f13faad5cb7d
Create Date: 2021-12-24 15:32:28.204704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ca64e311ab7'
down_revision = 'f13faad5cb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_comment_t_ibfk_1', 'blog_comment_t', type_='foreignkey')
    op.add_column('enum_config', sa.Column('parent_code', sa.String(length=255), server_default='-1', nullable=True, comment='父级code'))
    op.alter_column('enum_config', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               nullable=False,
               comment='枚举key值, 唯一(相当于自带路径)',
               existing_comment='枚举key值')
    op.alter_column('enum_config', 'value',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=False,
               existing_comment='枚举value数据')
    op.drop_index('create_by', table_name='enum_config')
    op.drop_index('create_by_2', table_name='enum_config')
    op.create_unique_constraint(None, 'enum_config', ['parent_code', 'value'])
    op.drop_column('enum_config', 'parent_id')
    op.drop_constraint('goods_t_ibfk_1', 'goods_t', type_='foreignkey')
    op.drop_constraint('message_comment_t_ibfk_1', 'message_comment_t', type_='foreignkey')
    op.drop_constraint('order_t_ibfk_1', 'order_t', type_='foreignkey')
    op.drop_constraint('order_t_ibfk_2', 'order_t', type_='foreignkey')
    op.drop_constraint('prove_vo_ibfk_1', 'prove_vo', type_='foreignkey')
    op.drop_constraint('story_vo_ibfk_1', 'story_vo', type_='foreignkey')
    op.drop_constraint('target_t_ibfk_1', 'target_t', type_='foreignkey')
    op.add_column('user', sa.Column('describe', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('id_card', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('business_license', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('resume', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('tiktok_number', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('video_number', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('wechat_number', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=255), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=12),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               nullable=False)
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.alter_column('user_cloud_space', 'file_name',
               existing_type=mysql.VARCHAR(length=150),
               comment='xxx.txt',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'file_path',
               existing_type=mysql.VARCHAR(length=150),
               comment='/xxx/xxx.txt',
               existing_nullable=True)
    op.drop_constraint('worker_time_t_ibfk_1', 'worker_time_t', type_='foreignkey')
    op.drop_constraint('works_t_ibfk_1', 'works_t', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('works_t_ibfk_1', 'works_t', 'video_user_t', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('worker_time_t_ibfk_1', 'worker_time_t', 'worker_t', ['worker_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_cloud_space', 'file_path',
               existing_type=mysql.VARCHAR(length=150),
               comment=None,
               existing_comment='/xxx/xxx.txt',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'file_name',
               existing_type=mysql.VARCHAR(length=150),
               comment=None,
               existing_comment='xxx.txt',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=12),
               nullable=True)
    op.drop_column('user', 'role')
    op.drop_column('user', 'wechat_number')
    op.drop_column('user', 'video_number')
    op.drop_column('user', 'tiktok_number')
    op.drop_column('user', 'resume')
    op.drop_column('user', 'brand')
    op.drop_column('user', 'business_license')
    op.drop_column('user', 'id_card')
    op.drop_column('user', 'describe')
    op.create_foreign_key('target_t_ibfk_1', 'target_t', 'video_user_t', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('story_vo_ibfk_1', 'story_vo', 'user', ['userId'], ['id'])
    op.create_foreign_key('prove_vo_ibfk_1', 'prove_vo', 'user', ['userId'], ['id'])
    op.create_foreign_key('order_t_ibfk_2', 'order_t', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_t_ibfk_1', 'order_t', 'goods_t', ['goods_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('message_comment_t_ibfk_1', 'message_comment_t', 'person_speech_t', ['personSpeechId'], ['id'])
    op.create_foreign_key('goods_t_ibfk_1', 'goods_t', 'store_t', ['store_id'], ['id'], ondelete='CASCADE')
    op.add_column('enum_config', sa.Column('parent_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='父级id'))
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.create_index('create_by_2', 'enum_config', ['create_by', 'parent_id', 'group_code', 'code'], unique=False)
    op.create_index('create_by', 'enum_config', ['create_by', 'parent_id', 'group_code', 'value'], unique=False)
    op.alter_column('enum_config', 'value',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=True,
               existing_comment='枚举value数据')
    op.alter_column('enum_config', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               nullable=True,
               comment='枚举key值',
               existing_comment='枚举key值, 唯一(相当于自带路径)')
    op.drop_column('enum_config', 'parent_code')
    op.create_foreign_key('blog_comment_t_ibfk_1', 'blog_comment_t', 'blog_t', ['blog_id'], ['id'])
    # ### end Alembic commands ###
