"""empty message

Revision ID: 4e55e8b7230e
Revises: de9302122973
Create Date: 2021-04-10 12:23:02.435424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e55e8b7230e'
down_revision = 'de9302122973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_t', sa.Column('start', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works_t', 'start')
    # ### end Alembic commands ###
