"""empty message

Revision ID: 50356d19c5e6
Revises: af26f6e95668
Create Date: 2022-02-22 00:34:55.702249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50356d19c5e6'
down_revision = 'af26f6e95668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_t', 'order_code',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=256),
               existing_comment='订单编号',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_t', 'order_code',
               existing_type=sa.String(length=256),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='订单编号',
               existing_nullable=True)
    # ### end Alembic commands ###
