"""empty message

Revision ID: 506b9e4ce2a8
Revises: 
Create Date: 2020-01-03 01:38:48.511300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506b9e4ce2a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('images', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_title'), 'announcement', ['title'], unique=False)
    op.create_index(op.f('ix_announcement_userid'), 'announcement', ['userid'], unique=False)
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('level', sa.String(length=70), nullable=True),
    sa.Column('position', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_member_relation',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('areaId', sa.String(length=150), nullable=True),
    sa.Column('userId', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('up_files', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.String(length=150), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enum_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('identity', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity')
    )
    op.create_index(op.f('ix_enum_config_name'), 'enum_config', ['name'], unique=False)
    op.create_table('member_user_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_user_t_name'), 'member_user_t', ['name'], unique=False)
    op.create_index(op.f('ix_member_user_t_phone'), 'member_user_t', ['phone'], unique=False)
    op.create_index(op.f('ix_member_user_t_store_id'), 'member_user_t', ['store_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=70), nullable=True),
    sa.Column('full_path_code', sa.String(length=70), nullable=True),
    sa.Column('full_path_id', sa.String(length=70), nullable=True),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_member_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('level', sa.String(length=70), nullable=True),
    sa.Column('full_name', sa.String(length=70), nullable=True),
    sa.Column('full_path', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.Column('video', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('store_name', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_t_name'), 'store_t', ['name'], unique=False)
    op.create_index(op.f('ix_store_t_phone'), 'store_t', ['phone'], unique=False)
    op.create_index(op.f('ix_store_t_store_name'), 'store_t', ['store_name'], unique=False)
    op.create_table('test_child_n_n_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_child_n_n_t_name'), 'test_child_n_n_t', ['name'], unique=False)
    op.create_table('test_parent_1_to_n_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_parent_n_n_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_parent_n_n_t_name'), 'test_parent_n_n_t', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('icon', sa.BLOB(length=300), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('user_cloud_space',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=150), nullable=True),
    sa.Column('file_path', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_n_n_t',
    sa.Column('test_parent_n_n_t_id', sa.Integer(), nullable=True),
    sa.Column('test_child_n_n_t_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_child_n_n_t_id'], ['test_child_n_n_t.id'], ),
    sa.ForeignKeyConstraint(['test_parent_n_n_t_id'], ['test_parent_n_n_t.id'], )
    )
    op.create_table('blog_comment_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_t.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_child_1_to_n_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['test_parent_1_to_n_t.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_child_1_to_n_t')
    op.drop_table('blog_comment_t')
    op.drop_table('association_n_n_t')
    op.drop_table('wallet_t')
    op.drop_table('user_cloud_space')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_test_parent_n_n_t_name'), table_name='test_parent_n_n_t')
    op.drop_table('test_parent_n_n_t')
    op.drop_table('test_parent_1_to_n_t')
    op.drop_index(op.f('ix_test_child_n_n_t_name'), table_name='test_child_n_n_t')
    op.drop_table('test_child_n_n_t')
    op.drop_index(op.f('ix_store_t_store_name'), table_name='store_t')
    op.drop_index(op.f('ix_store_t_phone'), table_name='store_t')
    op.drop_index(op.f('ix_store_t_name'), table_name='store_t')
    op.drop_table('store_t')
    op.drop_table('record')
    op.drop_table('project_config')
    op.drop_table('organization_member_relation')
    op.drop_table('organization')
    op.drop_table('message')
    op.drop_index(op.f('ix_member_user_t_store_id'), table_name='member_user_t')
    op.drop_index(op.f('ix_member_user_t_phone'), table_name='member_user_t')
    op.drop_index(op.f('ix_member_user_t_name'), table_name='member_user_t')
    op.drop_table('member_user_t')
    op.drop_index(op.f('ix_enum_config_name'), table_name='enum_config')
    op.drop_table('enum_config')
    op.drop_table('comment')
    op.drop_table('blog_t')
    op.drop_table('auth')
    op.drop_table('area_member_relation')
    op.drop_table('area')
    op.drop_index(op.f('ix_announcement_userid'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_title'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
