"""empty message

Revision ID: 515b722fd8a3
Revises: bc80ee0b2926
Create Date: 2022-01-17 23:27:26.080322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '515b722fd8a3'
down_revision = 'bc80ee0b2926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_time_t2_worker_id', table_name='worker_time_t2')
    op.drop_index('worker_id', table_name='worker_time_t2')
    op.drop_table('worker_time_t2')
    op.drop_constraint('role_permission_t_ibfk_1', 'role_permission_t', type_='foreignkey')
    op.drop_constraint('role_permission_t_ibfk_2', 'role_permission_t', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission_t', 'enum_config', ['permission'], ['code'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission_t', 'enum_config', ['role'], ['code'], ondelete='CASCADE')
    op.drop_constraint('user_role_t_ibfk_1', 'user_role_t', type_='foreignkey')
    op.create_foreign_key(None, 'user_role_t', 'enum_config', ['role'], ['code'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role_t', type_='foreignkey')
    op.create_foreign_key('user_role_t_ibfk_1', 'user_role_t', 'enum_config', ['role'], ['code'])
    op.drop_constraint(None, 'role_permission_t', type_='foreignkey')
    op.drop_constraint(None, 'role_permission_t', type_='foreignkey')
    op.create_foreign_key('role_permission_t_ibfk_2', 'role_permission_t', 'enum_config', ['role'], ['code'])
    op.create_foreign_key('role_permission_t_ibfk_1', 'role_permission_t', 'enum_config', ['permission'], ['code'])
    op.create_table('worker_time_t2',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('time_type', mysql.ENUM('morning', 'noon', 'afternoon', 'night'), nullable=True),
    sa.Column('worker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('worker_id', 'worker_time_t2', ['worker_id', 'date'], unique=False)
    op.create_index('ix_worker_time_t2_worker_id', 'worker_time_t2', ['worker_id'], unique=False)
    # ### end Alembic commands ###
