"""empty message

Revision ID: 538ab916bb1c
Revises: 8fe0d219e2e3
Create Date: 2022-01-10 18:23:54.379997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538ab916bb1c'
down_revision = '8fe0d219e2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('invitation_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_code_t')
    # ### end Alembic commands ###
