"""empty message

Revision ID: 53ce361ab89a
Revises: 26aa3ae4bf83
Create Date: 2021-02-03 23:49:36.164855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ce361ab89a'
down_revision = '26aa3ae4bf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_t', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_goods_t_store_id'), 'goods_t', ['store_id'], unique=False)
    op.create_foreign_key(None, 'goods_t', 'store_t', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods_t', type_='foreignkey')
    op.drop_index(op.f('ix_goods_t_store_id'), table_name='goods_t')
    op.drop_column('goods_t', 'store_id')
    # ### end Alembic commands ###
