"""empty message

Revision ID: 546329c4ee4b
Revises: 0a5b123d9ba3
Create Date: 2023-10-29 23:43:31.525187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '546329c4ee4b'
down_revision = '0a5b123d9ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_t', sa.Column('type_id', sa.String(length=256), nullable=True, comment='分类'))
    op.drop_column('goods_t', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_t', sa.Column('label', mysql.VARCHAR(length=256), nullable=True, comment='分类'))
    op.drop_column('goods_t', 'type_id')
    # ### end Alembic commands ###
