"""empty message

Revision ID: 58482f02b8d9
Revises: 62bc549019f8
Create Date: 2022-01-02 12:17:56.910356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58482f02b8d9'
down_revision = '62bc549019f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='注释',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               comment='注释',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###
