"""empty message

Revision ID: 58c0f23019a6
Revises: edba4566f94a
Create Date: 2022-02-21 14:55:05.355435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58c0f23019a6'
down_revision = 'edba4566f94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_t', 'price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               nullable=False,
               existing_comment='价格')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_t', 'price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               nullable=True,
               existing_comment='价格')
    # ### end Alembic commands ###
