"""empty message

Revision ID: 5b218121ebba
Revises: 0699f53da806
Create Date: 2020-08-09 01:27:35.592044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b218121ebba'
down_revision = '0699f53da806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('worker_time_t_ibfk_1', 'worker_time_t', type_='foreignkey')
    op.create_foreign_key(None, 'worker_time_t', 'worker_t', ['worker_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_time_t', type_='foreignkey')
    op.create_foreign_key('worker_time_t_ibfk_1', 'worker_time_t', 'worker_t', ['worker_id'], ['id'])
    # ### end Alembic commands ###
