"""empty message

Revision ID: 5b6faf865f81
Revises: 506b9e4ce2a8
Create Date: 2020-02-20 13:59:45.800273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b6faf865f81'
down_revision = '506b9e4ce2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_speech_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('group', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attention_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_t_group'), 'attention_t', ['group'], unique=False)
    op.create_index(op.f('ix_attention_t_userId'), 'attention_t', ['userId'], unique=False)
    op.create_table('message_comment_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('personSpeechId', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['personSpeechId'], ['person_speech_t.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('icon', sa.BLOB(length=300), nullable=True),
    sa.Column('weChatId', sa.String(length=60), nullable=True),
    sa.Column('idCard', sa.String(length=60), nullable=True),
    sa.Column('home', sa.String(length=60), nullable=True),
    sa.Column('motto', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_userId'), 'user_info', ['userId'], unique=False)
    op.add_column('user', sa.Column('userType', sa.Integer(), nullable=True))
    op.drop_column('user', 'icon')
    op.drop_column('user', 'email')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'active')
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('user', sa.Column('icon', sa.BLOB(), nullable=True))
    op.drop_column('user', 'userType')
    op.drop_index(op.f('ix_user_info_userId'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_table('message_comment_t')
    op.drop_index(op.f('ix_attention_t_userId'), table_name='attention_t')
    op.drop_index(op.f('ix_attention_t_group'), table_name='attention_t')
    op.drop_table('attention_t')
    op.drop_table('person_speech_t')
    # ### end Alembic commands ###
