"""empty message

Revision ID: 5be952d87cca
Revises: 
Create Date: 2021-11-08 15:02:49.987863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5be952d87cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_t_userId', table_name='model_t')
    op.drop_table('model_t')
    op.drop_table('setting_config')
    op.drop_constraint('prove_vo_ibfk_1', 'prove_vo', type_='foreignkey')
    op.create_foreign_key(None, 'prove_vo', 'user', ['userId'], ['id'])
    op.drop_constraint('story_vo_ibfk_1', 'story_vo', type_='foreignkey')
    op.create_foreign_key(None, 'story_vo', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_vo', type_='foreignkey')
    op.create_foreign_key('story_vo_ibfk_1', 'story_vo', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'prove_vo', type_='foreignkey')
    op.create_foreign_key('prove_vo_ibfk_1', 'prove_vo', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_table('setting_config',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('model_t',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=70), nullable=True),
    sa.Column('value', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_model_t_userId', 'model_t', ['userId'], unique=False)
    # ### end Alembic commands ###
