"""empty message

Revision ID: 5f5782abbd3d
Revises: 7aecf1967665
Create Date: 2022-03-07 23:38:01.370477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5782abbd3d'
down_revision = '7aecf1967665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'business_license')
    op.drop_column('user', 'brand')
    op.drop_column('user', 'resume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('brand', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('business_license', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
