"""empty message

Revision ID: 62bc549019f8
Revises: 99592a38c08c
Create Date: 2022-01-02 00:54:04.177359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62bc549019f8'
down_revision = '99592a38c08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_time_t2', sa.Column('area', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t2', sa.Column('content', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t2', sa.Column('time_type', sa.Enum('morning', 'noon', 'afternoon', 'night'), nullable=True))
    op.add_column('worker_time_t2', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_worker_time_t2_worker_id'), 'worker_time_t2', ['worker_id'], unique=False)
    op.create_unique_constraint(None, 'worker_time_t2', ['worker_id', 'date'])
    op.drop_column('worker_time_t2', 'noon_start')
    op.drop_column('worker_time_t2', 'name')
    op.drop_column('worker_time_t2', 'morning_end')
    op.drop_column('worker_time_t2', 'note')
    op.drop_column('worker_time_t2', 'noon_end')
    op.drop_column('worker_time_t2', 'json_data2')
    op.drop_column('worker_time_t2', 'evening_start')
    op.drop_column('worker_time_t2', 'json_data')
    op.drop_column('worker_time_t2', 'afternoon_end')
    op.drop_column('worker_time_t2', 'evening_end')
    op.drop_column('worker_time_t2', 'morning_start')
    op.drop_column('worker_time_t2', 'afternoon_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_time_t2', sa.Column('afternoon_start', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('morning_start', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('evening_end', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('afternoon_end', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('json_data', mysql.JSON(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('evening_start', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('json_data2', mysql.JSON(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('noon_end', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('note', mysql.VARCHAR(length=255), server_default=sa.text("'123'"), nullable=True))
    op.add_column('worker_time_t2', sa.Column('morning_end', mysql.TIME(), nullable=True))
    op.add_column('worker_time_t2', sa.Column('name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('worker_time_t2', sa.Column('noon_start', mysql.TIME(), nullable=True))
    op.drop_constraint(None, 'worker_time_t2', type_='unique')
    op.drop_index(op.f('ix_worker_time_t2_worker_id'), table_name='worker_time_t2')
    op.drop_column('worker_time_t2', 'worker_id')
    op.drop_column('worker_time_t2', 'time_type')
    op.drop_column('worker_time_t2', 'content')
    op.drop_column('worker_time_t2', 'area')
    # ### end Alembic commands ###
