"""empty message

Revision ID: 6a68c966e461
Revises: 04a05ecff956
Create Date: 2021-10-22 01:37:29.525264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a68c966e461'
down_revision = '04a05ecff956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ObjectVO',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProtocolVO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProveVO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=70), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('wight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProveVO_userId'), 'ProveVO', ['userId'], unique=False)
    op.create_table('StoryVO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=70), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('wight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StoryVO_userId'), 'StoryVO', ['userId'], unique=False)
    op.drop_index('ix_ProveVO_userId', table_name='provevo')
    op.drop_table('provevo')
    op.drop_table('objectvo')
    op.drop_index('ix_StoryVO_userId', table_name='storyvo')
    op.drop_table('storyvo')
    op.drop_table('protocolvo')
    op.add_column('enum_config', sa.Column('create_by', sa.String(length=255), server_default='SYSTEM', nullable=True, comment='创建者'))
    op.add_column('enum_config', sa.Column('group_code', sa.String(length=255), nullable=True, comment='分组code'))
    op.add_column('enum_config', sa.Column('parent_id', sa.Integer(), server_default='0', nullable=True, comment='父级id'))
    op.alter_column('enum_config', 'sort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='排序字段',
               existing_nullable=True)
    op.alter_column('enum_config', 'value',
               existing_type=mysql.VARCHAR(length=50),
               comment='枚举value数据',
               existing_nullable=True)
    op.drop_index('identity', table_name='enum_config')
    op.drop_index('ix_enum_config_name', table_name='enum_config')
    op.create_unique_constraint(None, 'enum_config', ['group_code'])
    op.create_unique_constraint(None, 'enum_config', ['code'])
    op.drop_column('enum_config', 'note')
    op.drop_column('enum_config', 'identity')
    op.drop_column('enum_config', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enum_config', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('enum_config', sa.Column('identity', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('enum_config', sa.Column('note', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.create_index('ix_enum_config_name', 'enum_config', ['name'], unique=False)
    op.create_index('identity', 'enum_config', ['identity'], unique=True)
    op.alter_column('enum_config', 'value',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='枚举value数据',
               existing_nullable=True)
    op.alter_column('enum_config', 'sort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='排序字段',
               existing_nullable=True)
    op.drop_column('enum_config', 'parent_id')
    op.drop_column('enum_config', 'group_code')
    op.drop_column('enum_config', 'create_by')
    op.create_table('protocolvo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('storyvo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('path', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('wight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='storyvo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_StoryVO_userId', 'storyvo', ['userId'], unique=False)
    op.create_table('objectvo',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('provevo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('path', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('wight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='provevo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ProveVO_userId', 'provevo', ['userId'], unique=False)
    op.drop_index(op.f('ix_StoryVO_userId'), table_name='StoryVO')
    op.drop_table('StoryVO')
    op.drop_index(op.f('ix_ProveVO_userId'), table_name='ProveVO')
    op.drop_table('ProveVO')
    op.drop_table('ProtocolVO')
    op.drop_table('ObjectVO')
    # ### end Alembic commands ###
