"""empty message

Revision ID: 6b8fb1054534
Revises: 
Create Date: 2021-10-22 23:27:12.756826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b8fb1054534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prove_vo', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('prove_vo', 'path')
    op.add_column('story_vo', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('story_vo', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_vo', sa.Column('path', mysql.VARCHAR(length=70), nullable=True))
    op.drop_column('story_vo', 'parent_id')
    op.add_column('prove_vo', sa.Column('path', mysql.VARCHAR(length=70), nullable=True))
    op.drop_column('prove_vo', 'parent_id')
    # ### end Alembic commands ###
