"""empty message

Revision ID: 6be40a8c38bb
Revises: 546329c4ee4b
Create Date: 2024-04-06 14:43:17.362822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6be40a8c38bb'
down_revision = '546329c4ee4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_t', sa.Column('image', sa.String(length=256), nullable=True))
    op.drop_column('goods_t', 'images')
    op.add_column('order_info_t', sa.Column('image', sa.String(length=256), nullable=True, comment='商品图片path'))
    op.add_column('order_info_t', sa.Column('name', sa.String(length=256), nullable=True, comment='商品名'))
    op.add_column('order_info_t', sa.Column('describe', sa.String(length=256), nullable=True, comment='介绍'))
    op.drop_index('ix_order_info_t_goods_name', table_name='order_info_t')
    op.drop_column('order_info_t', 'goods_img')
    op.drop_column('order_info_t', 'goods_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info_t', sa.Column('goods_name', mysql.VARCHAR(length=256), nullable=True, comment='商品名'))
    op.add_column('order_info_t', sa.Column('goods_img', mysql.VARCHAR(length=256), nullable=True, comment='商品图片path'))
    op.create_index('ix_order_info_t_goods_name', 'order_info_t', ['goods_name'], unique=False)
    op.drop_column('order_info_t', 'describe')
    op.drop_column('order_info_t', 'name')
    op.drop_column('order_info_t', 'image')
    op.add_column('goods_t', sa.Column('images', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('goods_t', 'image')
    # ### end Alembic commands ###
