"""empty message

Revision ID: 6c3f133aa575
Revises: af7ee36a2d00
Create Date: 2020-08-03 23:37:44.901658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c3f133aa575'
down_revision = 'af7ee36a2d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StoreMemberTable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StoreMemberTable_store_id'), 'StoreMemberTable', ['store_id'], unique=False)
    op.create_index(op.f('ix_StoreMemberTable_user_id'), 'StoreMemberTable', ['user_id'], unique=False)
    op.drop_index('ix_StoreMemberTable_store_id', table_name='storemembertable')
    op.drop_index('ix_StoreMemberTable_user_id', table_name='storemembertable')
    op.drop_table('storemembertable')
    op.drop_constraint('association_n_n_t_ibfk_2', 'association_n_n_t', type_='foreignkey')
    op.drop_constraint('association_n_n_t_ibfk_1', 'association_n_n_t', type_='foreignkey')
    op.create_foreign_key(None, 'association_n_n_t', 'test_child_n_n_t', ['test_child_n_n_t_id'], ['id'])
    op.create_foreign_key(None, 'association_n_n_t', 'test_parent_n_n_t', ['test_parent_n_n_t_id'], ['id'])
    op.drop_constraint('attention_t_ibfk_2', 'attention_t', type_='foreignkey')
    op.drop_constraint('attention_t_ibfk_1', 'attention_t', type_='foreignkey')
    op.create_foreign_key(None, 'attention_t', 'user', ['userId'], ['id'])
    op.create_foreign_key(None, 'attention_t', 'user', ['attentionUserId'], ['id'])
    op.drop_constraint('blog_comment_t_ibfk_1', 'blog_comment_t', type_='foreignkey')
    op.create_foreign_key(None, 'blog_comment_t', 'blog_t', ['blog_id'], ['id'])
    op.drop_constraint('message_comment_t_ibfk_1', 'message_comment_t', type_='foreignkey')
    op.create_foreign_key(None, 'message_comment_t', 'person_speech_t', ['personSpeechId'], ['id'])
    op.drop_constraint('model_t_ibfk_1', 'model_t', type_='foreignkey')
    op.create_foreign_key(None, 'model_t', 'user', ['userId'], ['id'])
    op.drop_constraint('test_child_1_to_n_t_ibfk_1', 'test_child_1_to_n_t', type_='foreignkey')
    op.create_foreign_key(None, 'test_child_1_to_n_t', 'test_parent_1_to_n_t', ['parent_id'], ['id'])
    op.drop_constraint('user_info_ibfk_1', 'user_info', type_='foreignkey')
    op.create_foreign_key(None, 'user_info', 'user', ['userId'], ['id'])
    op.add_column('worker_t', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_t', 'name')
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.create_foreign_key('user_info_ibfk_1', 'user_info', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'test_child_1_to_n_t', type_='foreignkey')
    op.create_foreign_key('test_child_1_to_n_t_ibfk_1', 'test_child_1_to_n_t', 'test_parent_1_to_n_t', ['parent_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'model_t', type_='foreignkey')
    op.create_foreign_key('model_t_ibfk_1', 'model_t', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'message_comment_t', type_='foreignkey')
    op.create_foreign_key('message_comment_t_ibfk_1', 'message_comment_t', 'person_speech_t', ['personSpeechId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'blog_comment_t', type_='foreignkey')
    op.create_foreign_key('blog_comment_t_ibfk_1', 'blog_comment_t', 'blog_t', ['blog_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'attention_t', type_='foreignkey')
    op.drop_constraint(None, 'attention_t', type_='foreignkey')
    op.create_foreign_key('attention_t_ibfk_1', 'attention_t', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('attention_t_ibfk_2', 'attention_t', 'user', ['attentionUserId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'association_n_n_t', type_='foreignkey')
    op.drop_constraint(None, 'association_n_n_t', type_='foreignkey')
    op.create_foreign_key('association_n_n_t_ibfk_1', 'association_n_n_t', 'test_child_n_n_t', ['test_child_n_n_t_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('association_n_n_t_ibfk_2', 'association_n_n_t', 'test_parent_n_n_t', ['test_parent_n_n_t_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_table('storemembertable',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_StoreMemberTable_user_id', 'storemembertable', ['user_id'], unique=False)
    op.create_index('ix_StoreMemberTable_store_id', 'storemembertable', ['store_id'], unique=False)
    op.drop_index(op.f('ix_StoreMemberTable_user_id'), table_name='StoreMemberTable')
    op.drop_index(op.f('ix_StoreMemberTable_store_id'), table_name='StoreMemberTable')
    op.drop_table('StoreMemberTable')
    # ### end Alembic commands ###
