"""empty message

Revision ID: 6e4c5c4ca5eb
Revises: 997556b0ce55
Create Date: 2022-02-20 18:46:39.780478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4c5c4ca5eb'
down_revision = '997556b0ce55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_t_store_id'), 'order_t', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_t_store_id'), table_name='order_t')
    op.drop_column('order_t', 'store_id')
    # ### end Alembic commands ###
