"""empty message

Revision ID: 7138e0255705
Revises: 
Create Date: 2020-04-29 00:06:07.608169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7138e0255705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=70), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('wight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_t_userId'), 'model_t', ['userId'], unique=False)
    op.create_index(op.f('ix_attention_t_attentionUserId'), 'attention_t', ['attentionUserId'], unique=False)
    op.create_foreign_key(None, 'attention_t', 'user', ['attentionUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attention_t', type_='foreignkey')
    op.drop_index(op.f('ix_attention_t_attentionUserId'), table_name='attention_t')
    op.drop_index(op.f('ix_model_t_userId'), table_name='model_t')
    op.drop_table('model_t')
    # ### end Alembic commands ###
