"""empty message

Revision ID: 788b2b71311f
Revises: 8675bd539082
Create Date: 2021-12-07 13:21:26.651906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788b2b71311f'
down_revision = '8675bd539082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'worker_t',
        '工人详情',
        existing_comment='工人详情表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'worker_t',
        '工人详情表',
        existing_comment='工人详情',
        schema=None
    )
    # ### end Alembic commands ###
