"""empty message

Revision ID: 7e7fde41fbd6
Revises: 2ee0be6df2da
Create Date: 2022-02-20 13:48:28.139793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e7fde41fbd6'
down_revision = '2ee0be6df2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('table_id', sa.String(length=255), nullable=True, comment='下单桌号'))
    op.alter_column('store_member_t', 'user_type',
               existing_type=mysql.VARCHAR(length=256),
               comment='枚举值: NormalVip:普通Vip; HighVip:高级Vip; TopVip:顶级Vip; Admin:管理员; Kitchen:厨师; NormalEmp:店员; StoreAdmin:店长;',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_member_t', 'user_type',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='枚举值: NormalVip:普通Vip; HighVip:高级Vip; TopVip:顶级Vip; Admin:管理员; Kitchen:厨师; NormalEmp:店员; StoreAdmin:店长;',
               existing_nullable=True)
    op.drop_column('order_t', 'table_id')
    # ### end Alembic commands ###
