"""empty message

Revision ID: 820187782143
Revises: f6703ac031a4
Create Date: 2022-02-10 10:11:50.896748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '820187782143'
down_revision = 'f6703ac031a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_t', 'price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='价格',
               existing_nullable=True)
    op.alter_column('goods_t', 'duration',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='折扣?',
               existing_nullable=True)
    op.alter_column('order_t', 'total_price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='总价',
               existing_nullable=True)
    op.alter_column('target_t', 'price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='价格',
               existing_nullable=True)
    op.alter_column('wallet_t', 'money',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='余额',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_t', 'money',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment=None,
               existing_comment='余额',
               existing_nullable=True)
    op.alter_column('target_t', 'price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment=None,
               existing_comment='价格',
               existing_nullable=True)
    op.alter_column('order_t', 'total_price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment=None,
               existing_comment='总价',
               existing_nullable=True)
    op.alter_column('goods_t', 'duration',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment=None,
               existing_comment='折扣?',
               existing_nullable=True)
    op.alter_column('goods_t', 'price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment=None,
               existing_comment='价格',
               existing_nullable=True)
    # ### end Alembic commands ###
