"""empty message

Revision ID: 83e3522ae9d1
Revises: 788b2b71311f
Create Date: 2021-12-13 00:17:19.992693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e3522ae9d1'
down_revision = '788b2b71311f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('group_code', table_name='enum_config')
    op.create_unique_constraint(None, 'enum_config', ['group_code', 'value'])
    op.create_unique_constraint(None, 'enum_config', ['group_code', 'code'])
    op.add_column('worker_time_t', sa.Column('afternoon_area', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('afternoon_content', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('morning_area', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('morning_content', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('night_area', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('night_content', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('noon_area', sa.String(length=255), nullable=True))
    op.add_column('worker_time_t', sa.Column('noon_content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_time_t', 'noon_content')
    op.drop_column('worker_time_t', 'noon_area')
    op.drop_column('worker_time_t', 'night_content')
    op.drop_column('worker_time_t', 'night_area')
    op.drop_column('worker_time_t', 'morning_content')
    op.drop_column('worker_time_t', 'morning_area')
    op.drop_column('worker_time_t', 'afternoon_content')
    op.drop_column('worker_time_t', 'afternoon_area')
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.create_index('group_code', 'enum_config', ['group_code'], unique=True)
    # ### end Alembic commands ###
