"""empty message

Revision ID: 853ef02128c5
Revises: 928af56bd045
Create Date: 2021-12-01 00:01:27.914379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '853ef02128c5'
down_revision = '928af56bd045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_member_relation')
    op.drop_table('class_t')
    op.drop_constraint('attention_t_ibfk_1', 'attention_t', type_='foreignkey')
    op.drop_constraint('attention_t_ibfk_2', 'attention_t', type_='foreignkey')
    op.create_foreign_key(None, 'attention_t', 'user', ['attentionUserId'], ['id'])
    op.create_foreign_key(None, 'attention_t', 'user', ['userId'], ['id'])
    op.drop_constraint('prove_vo_ibfk_1', 'prove_vo', type_='foreignkey')
    op.create_foreign_key(None, 'prove_vo', 'user', ['userId'], ['id'])
    op.drop_constraint('story_vo_ibfk_1', 'story_vo', type_='foreignkey')
    op.create_foreign_key(None, 'story_vo', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_vo', type_='foreignkey')
    op.create_foreign_key('story_vo_ibfk_1', 'story_vo', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'prove_vo', type_='foreignkey')
    op.create_foreign_key('prove_vo_ibfk_1', 'prove_vo', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'attention_t', type_='foreignkey')
    op.drop_constraint(None, 'attention_t', type_='foreignkey')
    op.create_foreign_key('attention_t_ibfk_2', 'attention_t', 'user', ['attentionUserId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('attention_t_ibfk_1', 'attention_t', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_table('class_t',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('describe', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('public', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('wight', mysql.FLOAT(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`deleted` in (0,1))', name='class_t_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('organization_member_relation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('full_path', mysql.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
