"""empty message

Revision ID: 85a389bad580
Revises: dd7a4a3db4aa
Create Date: 2022-02-18 19:08:33.050369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85a389bad580'
down_revision = 'dd7a4a3db4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default='-1',
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True)
    op.alter_column('goods_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('invitation_code_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('log_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('order_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('prove_vo', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('role_permission_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('store_member_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('store_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('story_vo', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('suggest_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('target_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('user', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('user_cloud_space', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('user_role_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('wallet_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('worker_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('worker_time_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('works_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建者的id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('worker_time_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('worker_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('wallet_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('user_role_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('user_cloud_space', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('user', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('target_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('suggest_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('story_vo', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('store_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('store_member_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('role_permission_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('prove_vo', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('order_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('log_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('invitation_code_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('goods_t', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default=sa.text("'-1'"),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('announcement', 'create_by',
               existing_type=mysql.INTEGER(),
               comment='创建者的id',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
    # ### end Alembic commands ###
