"""empty message

Revision ID: 8675bd539082
Revises: 853ef02128c5
Create Date: 2021-12-05 23:48:37.848160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8675bd539082'
down_revision = '853ef02128c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='创建者id',
               existing_comment='创建者',
               existing_nullable=True,
               existing_server_default=sa.text("'SYSTEM'"))
    op.create_unique_constraint(None, 'worker_t', ['belong', 'id_card_number'])
    op.create_table_comment(
        'worker_t',
        '工人详情表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'worker_t',
        existing_comment='工人详情表',
        schema=None
    )
    op.drop_constraint(None, 'worker_t', type_='unique')
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='创建者',
               existing_comment='创建者id',
               existing_nullable=True,
               existing_server_default=sa.text("'SYSTEM'"))
    op.create_table('auth',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('path', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
