"""empty message

Revision ID: 885f7a01dbf7
Revises: 820187782143
Create Date: 2022-02-17 01:11:32.343100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885f7a01dbf7'
down_revision = '820187782143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_t', sa.Column('label', sa.String(length=256), nullable=True, comment='分类'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods_t', 'label')
    # ### end Alembic commands ###
