"""empty message

Revision ID: 8ee170e031d3
Revises: d6806161e66c
Create Date: 2022-02-22 20:05:51.373808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ee170e031d3'
down_revision = 'd6806161e66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_announcement_userid', table_name='announcement')
    op.create_index(op.f('ix_announcement_user_id'), 'announcement', ['user_id'], unique=False)
    op.drop_column('announcement', 'userid')
    op.add_column('log_t', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_log_t_userId', table_name='log_t')
    op.create_index(op.f('ix_log_t_user_id'), 'log_t', ['user_id'], unique=False)
    op.drop_column('log_t', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_t', sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_log_t_user_id'), table_name='log_t')
    op.create_index('ix_log_t_userId', 'log_t', ['userId'], unique=False)
    op.drop_column('log_t', 'user_id')
    op.add_column('announcement', sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_announcement_user_id'), table_name='announcement')
    op.create_index('ix_announcement_userid', 'announcement', ['userid'], unique=False)
    op.drop_column('announcement', 'user_id')
    # ### end Alembic commands ###
