"""empty message

Revision ID: 8f0ba34400e4
Revises: 0b7146a1a3f8
Create Date: 2022-08-21 21:56:31.530875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f0ba34400e4'
down_revision = '0b7146a1a3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('js_form',
    sa.Column('TABLE_CATALOG', sa.String(length=64), nullable=False),
    sa.Column('TABLE_SCHEMA', sa.String(length=64), nullable=False),
    sa.Column('TABLE_NAME', sa.String(length=64), nullable=True),
    sa.Column('COLUMN_NAME', sa.String(length=64), nullable=False),
    sa.Column('ORDINAL_POSITION', sa.String(length=64), nullable=True),
    sa.Column('COLUMN_DEFAULT', sa.String(length=64), nullable=True),
    sa.Column('IS_NULLABLE', sa.String(length=64), nullable=True),
    sa.Column('DATA_TYPE', sa.String(length=64), nullable=True),
    sa.Column('CHARACTER_MAXIMUM_LENGTH', sa.String(length=64), nullable=True),
    sa.Column('CHARACTER_OCTET_LENGTH', sa.String(length=64), nullable=True),
    sa.Column('NUMERIC_PRECISION', sa.String(length=64), nullable=True),
    sa.Column('NUMERIC_SCALE', sa.String(length=64), nullable=True),
    sa.Column('DATETIME_PRECISION', sa.String(length=64), nullable=True),
    sa.Column('CHARACTER_SET_NAME', sa.String(length=64), nullable=True),
    sa.Column('COLLATION_NAME', sa.String(length=64), nullable=True),
    sa.Column('COLUMN_TYPE', sa.String(length=64), nullable=True),
    sa.Column('COLUMN_KEY', sa.String(length=64), nullable=True),
    sa.Column('EXTRA', sa.String(length=64), nullable=True),
    sa.Column('PRIVILEGES', sa.String(length=64), nullable=True),
    sa.Column('COLUMN_COMMENT', sa.String(length=64), nullable=True),
    sa.Column('GENERATION_EXPRESSION', sa.String(length=64), nullable=True),
    sa.Column('SRS_ID', sa.String(length=64), nullable=True),
    sa.Column('name_cn', sa.String(length=64), nullable=True),
    sa.Column('data_type2', sa.String(length=64), nullable=True),
    sa.Column('num_max', sa.String(length=64), nullable=True),
    sa.Column('num_min', sa.String(length=64), nullable=True),
    sa.Column('valid_regx', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('TABLE_CATALOG', 'TABLE_SCHEMA', 'COLUMN_NAME'),
    schema='code',
    comment='js_form',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('columns',
    sa.Column('TABLE_CATALOG', sa.String(length=64), nullable=False),
    sa.Column('TABLE_SCHEMA', sa.String(length=64), nullable=False),
    sa.Column('TABLE_NAME', sa.String(length=64), nullable=False, comment='表名'),
    sa.Column('COLUMN_NAME', sa.String(length=64), nullable=False, comment='字段名'),
    sa.Column('ORDINAL_POSITION', mysql.INTEGER(display_width=10), nullable=True, comment='顺序?'),
    sa.Column('COLUMN_DEFAULT', sa.Text(), nullable=True, comment='默认值'),
    sa.Column('IS_NULLABLE', sa.String(length=3), nullable=True, comment='是否可以None'),
    sa.Column('DATA_TYPE', mysql.LONGTEXT(), nullable=True, comment='数据类型'),
    sa.Column('CHARACTER_MAXIMUM_LENGTH', mysql.BIGINT(display_width=21), nullable=True, comment='字符串最大长度?'),
    sa.Column('CHARACTER_OCTET_LENGTH', mysql.BIGINT(display_width=21), nullable=True, comment='?'),
    sa.Column('NUMERIC_PRECISION', mysql.BIGINT(display_width=10), nullable=True, comment='??'),
    sa.Column('NUMERIC_SCALE', mysql.BIGINT(display_width=10), nullable=True, comment='?'),
    sa.Column('DATETIME_PRECISION', mysql.INTEGER(display_width=10), nullable=True, comment='?'),
    sa.Column('CHARACTER_SET_NAME', sa.String(length=64), nullable=True, comment='?'),
    sa.Column('COLLATION_NAME', sa.String(length=64), nullable=True, comment='表名'),
    sa.Column('COLUMN_TYPE', mysql.MEDIUMTEXT(), nullable=True, comment='??'),
    sa.Column('COLUMN_KEY', sa.Enum('', 'PRI', 'UNI', 'MUL'), nullable=True, comment='??'),
    sa.Column('EXTRA', sa.String(length=256), nullable=True, comment='表名'),
    sa.Column('PRIVILEGES', sa.String(length=154), nullable=True, comment='表名'),
    sa.Column('COLUMN_COMMENT', sa.Text(), nullable=True, comment='字段注释'),
    sa.Column('GENERATION_EXPRESSION', mysql.LONGTEXT(), nullable=True, comment='表名'),
    sa.Column('SRS_ID', mysql.INTEGER(display_width=10), nullable=True),
    sa.PrimaryKeyConstraint('TABLE_CATALOG', 'TABLE_SCHEMA', 'TABLE_NAME', 'COLUMN_NAME')
    )
    op.create_table('tables',
    sa.Column('TABLE_CATALOG', sa.String(length=64), nullable=False),
    sa.Column('TABLE_SCHEMA', sa.String(length=64), nullable=False),
    sa.Column('TABLE_NAME', sa.String(length=64), nullable=False),
    sa.Column('TABLE_TYPE', sa.Enum('BASE TABLE', 'VIEW', 'SYSTEM VIEW'), nullable=True),
    sa.Column('ENGINE', sa.String(length=64), nullable=True),
    sa.Column('VERSION', mysql.INTEGER(display_width=2), nullable=True),
    sa.Column('ROW_FORMAT', sa.Enum('Fixed', 'Dynamic', 'Compressed', 'Redundant', 'Compact', 'Paged'), nullable=True),
    sa.Column('TABLE_ROWS', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('AVG_ROW_LENGTH', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('DATA_LENGTH', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('MAX_DATA_LENGTH', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('INDEX_LENGTH', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('DATA_FREE', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('AUTO_INCREMENT', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('CREATE_TIME', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATE_TIME', sa.DateTime(), nullable=True),
    sa.Column('CHECK_TIME', sa.DateTime(), nullable=True),
    sa.Column('TABLE_COLLATION', sa.String(length=64), nullable=True),
    sa.Column('CHECKSUM', mysql.BIGINT(display_width=21), nullable=True),
    sa.Column('CREATE_OPTIONS', sa.String(length=256), nullable=True),
    sa.Column('TABLE_COMMENT', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('TABLE_CATALOG', 'TABLE_SCHEMA', 'TABLE_NAME')
    )
    op.alter_column('announcement', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('announcement', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('enum_config', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('enum_config', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('goods_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('goods_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('log_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('log_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.add_column('order_t', sa.Column('cooker_status', sa.String(length=256), nullable=True, comment='是否做完菜'))
    op.alter_column('order_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('order_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('prove_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('prove_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('qr_code_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('qr_code_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_member_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_member_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_role_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_role_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('story_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('story_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('suggest_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('suggest_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('system_level_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('system_level_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('target_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('target_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('target_t', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=1000),
               type_=sa.Text(),
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user_role_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_role_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('wallet_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('wallet_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'pay',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               type_=sa.Float(precision='12,4'),
               existing_comment='日薪资(元)',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('works_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('works_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='修改时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('works_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'pay',
               existing_type=sa.Float(precision='12,4'),
               type_=mysql.FLOAT(precision=10, scale=2),
               existing_comment='日薪资(元)',
               existing_nullable=True)
    op.alter_column('worker_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('wallet_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('wallet_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_role_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user_role_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('target_t', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=1000),
               existing_comment='内容',
               existing_nullable=True)
    op.alter_column('target_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('target_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('system_level_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('system_level_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('suggest_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('suggest_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('story_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('story_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_role_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_role_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_member_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_member_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('qr_code_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('qr_code_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('prove_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('prove_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('order_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('order_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('order_t', 'cooker_status')
    op.alter_column('log_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('log_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('goods_t', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('goods_t', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('enum_config', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('enum_config', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('announcement', 'update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('announcement', 'create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_table('tables')
    op.drop_table('columns')
    op.drop_table('js_form', schema='code')
    # ### end Alembic commands ###
