"""empty message

Revision ID: 8fe0d219e2e3
Revises: 9c3057cd48b3
Create Date: 2022-01-10 00:23:50.259212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe0d219e2e3'
down_revision = '9c3057cd48b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('goods_name', sa.Integer(), nullable=True))
    op.add_column('order_t', sa.Column('status', sa.String(length=255), nullable=True))
    op.add_column('order_t', sa.Column('total_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_order_t_goods_name'), 'order_t', ['goods_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_t_goods_name'), table_name='order_t')
    op.drop_column('order_t', 'total_price')
    op.drop_column('order_t', 'status')
    op.drop_column('order_t', 'goods_name')
    # ### end Alembic commands ###
