"""empty message

Revision ID: 90bbc7ced402
Revises: 0a5ded26fcdd
Create Date: 2021-03-30 23:26:48.179911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bbc7ced402'
down_revision = '0a5ded26fcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('invitation_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('video_user_t', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('video_user_t', sa.Column('tiktok_number', sa.String(length=255), nullable=True))
    op.add_column('video_user_t', sa.Column('video_number', sa.String(length=255), nullable=True))
    op.add_column('video_user_t', sa.Column('wechat_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_user_t', 'wechat_number')
    op.drop_column('video_user_t', 'video_number')
    op.drop_column('video_user_t', 'tiktok_number')
    op.drop_column('video_user_t', 'phone')
    op.drop_table('invitation_code_t')
    # ### end Alembic commands ###
