"""empty message

Revision ID: 928af56bd045
Revises: 5be952d87cca
Create Date: 2021-11-30 23:32:24.277427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '928af56bd045'
down_revision = '5be952d87cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('btree_t')
    op.drop_table('organization')
    op.drop_constraint('prove_vo_ibfk_1', 'prove_vo', type_='foreignkey')
    op.create_foreign_key(None, 'prove_vo', 'user', ['userId'], ['id'])
    op.drop_constraint('story_vo_ibfk_1', 'story_vo', type_='foreignkey')
    op.create_foreign_key(None, 'story_vo', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_vo', type_='foreignkey')
    op.create_foreign_key('story_vo_ibfk_1', 'story_vo', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'prove_vo', type_='foreignkey')
    op.create_foreign_key('prove_vo_ibfk_1', 'prove_vo', 'user', ['userId'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_table('organization',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150), nullable=True),
    sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=70), nullable=True),
    sa.Column('full_path_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=70), nullable=True),
    sa.Column('full_path_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=70), nullable=True),
    sa.Column('code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150), nullable=True),
    sa.Column('leader', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('btree_t',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('fullPath', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=70), nullable=True),
    sa.Column('value', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
