"""empty message

Revision ID: 9563e9cd6f13
Revises: e1e4b249bc0b
Create Date: 2022-02-09 15:14:31.035049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9563e9cd6f13'
down_revision = 'e1e4b249bc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_comment='枚举值 ReviewEnum',
               existing_nullable=True)
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_comment='枚举值 ReviewEnum',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值 ReviewEnum',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值 ReviewEnum',
               existing_comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_nullable=True)
    # ### end Alembic commands ###
