"""empty message

Revision ID: 9612144f06da
Revises: 515b722fd8a3
Create Date: 2022-01-17 23:29:30.785376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9612144f06da'
down_revision = '515b722fd8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_permission_t_ibfk_2', 'role_permission_t', type_='foreignkey')
    op.drop_constraint('role_permission_t_ibfk_1', 'role_permission_t', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission_t', 'enum_config', ['role'], ['code'], onupdate='CASCADE')
    op.create_foreign_key(None, 'role_permission_t', 'enum_config', ['permission'], ['code'], onupdate='CASCADE')
    op.drop_constraint('user_role_t_ibfk_1', 'user_role_t', type_='foreignkey')
    op.create_foreign_key(None, 'user_role_t', 'enum_config', ['role'], ['code'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role_t', type_='foreignkey')
    op.create_foreign_key('user_role_t_ibfk_1', 'user_role_t', 'enum_config', ['role'], ['code'], ondelete='CASCADE')
    op.drop_constraint(None, 'role_permission_t', type_='foreignkey')
    op.drop_constraint(None, 'role_permission_t', type_='foreignkey')
    op.create_foreign_key('role_permission_t_ibfk_1', 'role_permission_t', 'enum_config', ['permission'], ['code'], ondelete='CASCADE')
    op.create_foreign_key('role_permission_t_ibfk_2', 'role_permission_t', 'enum_config', ['role'], ['code'], ondelete='CASCADE')
    # ### end Alembic commands ###
