"""empty message

Revision ID: 9625f767acc8
Revises: 966b1a78b2ba
Create Date: 2022-02-10 00:39:18.110235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9625f767acc8'
down_revision = '966b1a78b2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_t', 'pay',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment='日薪资',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment='上午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment='中午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment='下午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'night',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment='晚上工时',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_time_t', 'night',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment=None,
               existing_comment='晚上工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment=None,
               existing_comment='下午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment=None,
               existing_comment='中午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment=None,
               existing_comment='上午工时',
               existing_nullable=True)
    op.alter_column('worker_t', 'pay',
               existing_type=mysql.FLOAT(precision=255, scale=0),
               comment=None,
               existing_comment='日薪资',
               existing_nullable=True)
    # ### end Alembic commands ###
