"""empty message

Revision ID: 966b1a78b2ba
Revises: de994d170b5d
Create Date: 2022-02-09 15:35:38.660163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '966b1a78b2ba'
down_revision = 'de994d170b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    # ### end Alembic commands ###
