"""empty message

Revision ID: 99592a38c08c
Revises: a96f32d0bd9c
Create Date: 2021-12-24 15:37:34.332271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99592a38c08c'
down_revision = 'a96f32d0bd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('sex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('icon', sa.BLOB(), nullable=True),
    sa.Column('weChatId', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('idCard', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('home', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('motto', mysql.VARCHAR(length=60), nullable=True),
    sa.CheckConstraint('(`sex` in (0,1))', name='user_info_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
