"""empty message

Revision ID: 997556b0ce55
Revises: 7e7fde41fbd6
Create Date: 2022-02-20 18:36:01.608813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '997556b0ce55'
down_revision = '7e7fde41fbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_t', 'status',
               existing_type=mysql.VARCHAR(length=255),
               comment='枚举值: PAYMENT_SUCCESS:支付完成; UN_PAYMENT:未支付;',
               existing_nullable=True)
    op.alter_column('order_t', 'total_price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='价格(每个)',
               existing_comment='总价',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_t', 'total_price',
               existing_type=mysql.FLOAT(precision=14, scale=2),
               comment='总价',
               existing_comment='价格(每个)',
               existing_nullable=True)
    op.alter_column('order_t', 'status',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='枚举值: PAYMENT_SUCCESS:支付完成; UN_PAYMENT:未支付;',
               existing_nullable=True)
    # ### end Alembic commands ###
