"""empty message

Revision ID: 9abe1f5299ed
Revises: 029e486a6732
Create Date: 2021-03-15 23:24:54.883456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9abe1f5299ed'
down_revision = '029e486a6732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_t', sa.Column('content', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_target_t_content'), 'target_t', ['content'], unique=False)
    op.drop_column('target_t', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_t', sa.Column('price', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_target_t_content'), table_name='target_t')
    op.drop_column('target_t', 'content')
    # ### end Alembic commands ###
