"""empty message

Revision ID: 9c474c1b7a25
Revises: f4f6bf4c0e53
Create Date: 2022-02-18 18:39:26.769012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c474c1b7a25'
down_revision = 'f4f6bf4c0e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default='-1',
               existing_comment='创建者id',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    # ### end Alembic commands ###
