"""empty message

Revision ID: 9c765e86a721
Revises: 
Create Date: 2020-06-27 18:22:04.198823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c765e86a721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_speech_t', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_speech_t', 'title')
    # ### end Alembic commands ###
