"""empty message

Revision ID: 9ff9f22fcac8
Revises: 885f7a01dbf7
Create Date: 2022-02-18 18:26:47.222444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ff9f22fcac8'
down_revision = '885f7a01dbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('announcement', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('announcement', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('announcement', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('enum_config', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('enum_config', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('enum_config', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('goods_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('goods_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('goods_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('goods_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('invitation_code_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('invitation_code_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('invitation_code_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('log_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('log_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('log_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('log_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('order_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('order_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('order_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('order_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('prove_vo', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('prove_vo', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('prove_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('prove_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('role_permission_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('role_permission_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('role_permission_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('store_member_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('store_member_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('store_member_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_member_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('store_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('store_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('store_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('store_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('story_vo', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('story_vo', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('story_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('story_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('suggest_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('suggest_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('suggest_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('suggest_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('target_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('target_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('target_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('target_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('user', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('user', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('user', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('user_cloud_space', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('user_cloud_space', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('user_cloud_space', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('user_role_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('user_role_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('user_role_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_role_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('wallet_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('wallet_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('wallet_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('wallet_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('worker_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('worker_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('worker_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('worker_time_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('worker_time_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('worker_time_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    op.add_column('works_t', sa.Column('create_by', sa.Integer(), server_default='-1', nullable=True, comment='创建者id'))
    op.add_column('works_t', sa.Column('update_by', sa.Integer(), server_default='-1', nullable=True, comment='修改者id'))
    op.alter_column('works_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('works_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('works_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('works_t', 'update_by')
    op.drop_column('works_t', 'create_by')
    op.alter_column('worker_time_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('worker_time_t', 'update_by')
    op.drop_column('worker_time_t', 'create_by')
    op.alter_column('worker_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('worker_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('worker_t', 'update_by')
    op.drop_column('worker_t', 'create_by')
    op.alter_column('wallet_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('wallet_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('wallet_t', 'update_by')
    op.drop_column('wallet_t', 'create_by')
    op.alter_column('user_role_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user_role_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('user_role_t', 'update_by')
    op.drop_column('user_role_t', 'create_by')
    op.alter_column('user_cloud_space', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('user_cloud_space', 'update_by')
    op.drop_column('user_cloud_space', 'create_by')
    op.alter_column('user', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('user', 'update_by')
    op.drop_column('user', 'create_by')
    op.alter_column('target_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('target_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('target_t', 'update_by')
    op.drop_column('target_t', 'create_by')
    op.alter_column('suggest_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('suggest_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('suggest_t', 'update_by')
    op.drop_column('suggest_t', 'create_by')
    op.alter_column('story_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('story_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('story_vo', 'update_by')
    op.drop_column('story_vo', 'create_by')
    op.alter_column('store_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('store_t', 'update_by')
    op.drop_column('store_t', 'create_by')
    op.alter_column('store_member_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('store_member_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('store_member_t', 'update_by')
    op.drop_column('store_member_t', 'create_by')
    op.alter_column('role_permission_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('role_permission_t', 'update_by')
    op.drop_column('role_permission_t', 'create_by')
    op.alter_column('prove_vo', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('prove_vo', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('prove_vo', 'update_by')
    op.drop_column('prove_vo', 'create_by')
    op.alter_column('order_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('order_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('order_t', 'update_by')
    op.drop_column('order_t', 'create_by')
    op.alter_column('log_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('log_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('log_t', 'update_by')
    op.drop_column('log_t', 'create_by')
    op.alter_column('invitation_code_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('invitation_code_t', 'update_by')
    op.drop_column('invitation_code_t', 'create_by')
    op.alter_column('goods_t', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('goods_t', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('goods_t', 'update_by')
    op.drop_column('goods_t', 'create_by')
    op.alter_column('enum_config', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('enum_config', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('enum_config', 'update_by')
    op.alter_column('announcement', 'update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('announcement', 'create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('announcement', 'update_by')
    op.drop_column('announcement', 'create_by')
    # ### end Alembic commands ###
