"""empty message

Revision ID: a1cd703ec517
Revises: 872764bee09d
Create Date: 2022-02-18 19:25:50.852855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1cd703ec517'
down_revision = '872764bee09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               type_=sa.String(length=128),
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state',
               existing_type=sa.String(length=128),
               type_=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    # ### end Alembic commands ###
