"""empty message

Revision ID: a51761b28989
Revises: 221d671aef92
Create Date: 2020-08-06 23:19:02.047289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a51761b28989'
down_revision = '221d671aef92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_t', sa.Column('phone', sa.String(length=11), nullable=True))
    op.create_unique_constraint(None, 'worker_t', ['id_card_number'])
    op.drop_column('worker_t', 'address')
    op.add_column('worker_time_t', sa.Column('afternoon', sa.Integer(), nullable=True))
    op.add_column('worker_time_t', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('worker_time_t', sa.Column('morning', sa.Integer(), nullable=True))
    op.add_column('worker_time_t', sa.Column('night', sa.Integer(), nullable=True))
    op.add_column('worker_time_t', sa.Column('noon', sa.Integer(), nullable=True))
    op.add_column('worker_time_t', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_worker_time_t_worker_id'), 'worker_time_t', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'worker_time_t', 'worker_t', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_time_t', type_='foreignkey')
    op.drop_index(op.f('ix_worker_time_t_worker_id'), table_name='worker_time_t')
    op.drop_column('worker_time_t', 'worker_id')
    op.drop_column('worker_time_t', 'noon')
    op.drop_column('worker_time_t', 'night')
    op.drop_column('worker_time_t', 'morning')
    op.drop_column('worker_time_t', 'date')
    op.drop_column('worker_time_t', 'afternoon')
    op.add_column('worker_t', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'worker_t', type_='unique')
    op.drop_column('worker_t', 'phone')
    # ### end Alembic commands ###
