"""empty message

Revision ID: a96f32d0bd9c
Revises: af4227d9d722
Create Date: 2021-12-24 15:37:16.018738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96f32d0bd9c'
down_revision = 'af4227d9d722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_info_userId', table_name='user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_info_userId', 'user_info', ['userId'], unique=False)
    # ### end Alembic commands ###
