"""empty message

Revision ID: af26f6e95668
Revises: 58c0f23019a6
Create Date: 2022-02-22 00:33:56.722360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af26f6e95668'
down_revision = '58c0f23019a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_t', sa.Column('order_code', sa.Integer(), nullable=True, comment='订单编号'))
    op.create_index(op.f('ix_order_t_order_code'), 'order_t', ['order_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_t_order_code'), table_name='order_t')
    op.drop_column('order_t', 'order_code')
    # ### end Alembic commands ###
