"""empty message

Revision ID: af4227d9d722
Revises: 4ca64e311ab7
Create Date: 2021-12-24 15:36:45.783901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4227d9d722'
down_revision = '4ca64e311ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_info_ibfk_1', 'user_info', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_info_ibfk_1', 'user_info', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###
