"""empty message

Revision ID: b1d695e100e0
Revises: 2128bc702a7d
Create Date: 2020-09-15 23:35:16.589553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d695e100e0'
down_revision = '2128bc702a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_card_number', table_name='worker_t')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_card_number', 'worker_t', ['id_card_number'], unique=True)
    # ### end Alembic commands ###
