"""empty message

Revision ID: b944dbdbc635
Revises: 27b9d3ee5c4c
Create Date: 2021-05-14 00:41:50.143832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b944dbdbc635'
down_revision = '27b9d3ee5c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_user_t', sa.Column('role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_user_t', 'role')
    # ### end Alembic commands ###
