"""empty message

Revision ID: bc80ee0b2926
Revises: 538ab916bb1c
Create Date: 2022-01-13 22:52:28.188000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc80ee0b2926'
down_revision = '538ab916bb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('permission', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['permission'], ['enum_config.code'], ),
    sa.ForeignKeyConstraint(['role'], ['enum_config.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['enum_config.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_t')
    op.drop_table('role_permission_t')
    # ### end Alembic commands ###
