"""empty message

Revision ID: bcd53fb5a631
Revises: 85a389bad580
Create Date: 2022-02-18 19:10:18.686138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd53fb5a631'
down_revision = '85a389bad580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default='-1',
               type_=sa.Integer(),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('enum_config', 'value',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               type_=sa.String(length=255),
               existing_comment='枚举value数据',
               existing_nullable=False)
    op.alter_column('store_t', 'password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_t', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('enum_config', 'value',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               existing_comment='枚举value数据',
               existing_nullable=False)
    op.alter_column('enum_config', 'create_by',
               existing_type=sa.Integer(),
               server_default=sa.text("'-1'"),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_comment='创建者id',
               existing_nullable=True)
    # ### end Alembic commands ###
