"""empty message

Revision ID: bd1aba265fe1
Revises: 
Create Date: 2020-08-23 23:59:23.814629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1aba265fe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('images', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_title'), 'announcement', ['title'], unique=False)
    op.create_index(op.f('ix_announcement_userid'), 'announcement', ['userid'], unique=False)
    op.create_table('auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('up_files', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('btree2_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('fullPath', sa.String(length=70), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('btree_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('fullPath', sa.String(length=70), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('describe', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('public', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('wight', sa.Float(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.String(length=150), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enum_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('identity', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity')
    )
    op.create_index(op.f('ix_enum_config_name'), 'enum_config', ['name'], unique=False)
    op.create_table('exist_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=70), nullable=True),
    sa.Column('full_path_code', sa.String(length=70), nullable=True),
    sa.Column('full_path_id', sa.String(length=70), nullable=True),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_member_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('level', sa.String(length=70), nullable=True),
    sa.Column('full_name', sa.String(length=70), nullable=True),
    sa.Column('full_path', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_speech_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.Column('video', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_member_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_member_t_store_id'), 'store_member_t', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_member_t_user_id'), 'store_member_t', ['user_id'], unique=False)
    op.create_table('store_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('store_name', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_t_name'), 'store_t', ['name'], unique=False)
    op.create_index(op.f('ix_store_t_phone'), 'store_t', ['phone'], unique=False)
    op.create_index(op.f('ix_store_t_store_name'), 'store_t', ['store_name'], unique=False)
    op.create_index(op.f('ix_store_t_user_id'), 'store_t', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('userType', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('user_cloud_space',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=150), nullable=True),
    sa.Column('file_path', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_t_store_id'), 'wallet_t', ['store_id'], unique=False)
    op.create_table('worker_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('belong', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('id_card_number', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('男', '女'), nullable=True),
    sa.Column('pay', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card_number')
    )
    op.create_table('attention_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('attentionUserId', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['attentionUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_t_attentionUserId'), 'attention_t', ['attentionUserId'], unique=False)
    op.create_index(op.f('ix_attention_t_group'), 'attention_t', ['group'], unique=False)
    op.create_index(op.f('ix_attention_t_userId'), 'attention_t', ['userId'], unique=False)
    op.create_table('blog_comment_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_t.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_comment_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('personSpeechId', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['personSpeechId'], ['person_speech_t.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=70), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('wight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_t_userId'), 'model_t', ['userId'], unique=False)
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('icon', sa.BLOB(length=300), nullable=True),
    sa.Column('weChatId', sa.String(length=60), nullable=True),
    sa.Column('idCard', sa.String(length=60), nullable=True),
    sa.Column('home', sa.String(length=60), nullable=True),
    sa.Column('motto', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_userId'), 'user_info', ['userId'], unique=False)
    op.create_table('worker_time_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('morning', sa.Integer(), nullable=True),
    sa.Column('noon', sa.Integer(), nullable=True),
    sa.Column('afternoon', sa.Integer(), nullable=True),
    sa.Column('night', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_t.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_time_t_worker_id'), 'worker_time_t', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_time_t_worker_id'), table_name='worker_time_t')
    op.drop_table('worker_time_t')
    op.drop_index(op.f('ix_user_info_userId'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_model_t_userId'), table_name='model_t')
    op.drop_table('model_t')
    op.drop_table('message_comment_t')
    op.drop_table('blog_comment_t')
    op.drop_index(op.f('ix_attention_t_userId'), table_name='attention_t')
    op.drop_index(op.f('ix_attention_t_group'), table_name='attention_t')
    op.drop_index(op.f('ix_attention_t_attentionUserId'), table_name='attention_t')
    op.drop_table('attention_t')
    op.drop_table('worker_t')
    op.drop_index(op.f('ix_wallet_t_store_id'), table_name='wallet_t')
    op.drop_table('wallet_t')
    op.drop_table('user_cloud_space')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_store_t_user_id'), table_name='store_t')
    op.drop_index(op.f('ix_store_t_store_name'), table_name='store_t')
    op.drop_index(op.f('ix_store_t_phone'), table_name='store_t')
    op.drop_index(op.f('ix_store_t_name'), table_name='store_t')
    op.drop_table('store_t')
    op.drop_index(op.f('ix_store_member_t_user_id'), table_name='store_member_t')
    op.drop_index(op.f('ix_store_member_t_store_id'), table_name='store_member_t')
    op.drop_table('store_member_t')
    op.drop_table('record')
    op.drop_table('project_config')
    op.drop_table('person_speech_t')
    op.drop_table('organization_member_relation')
    op.drop_table('organization')
    op.drop_table('message')
    op.drop_table('exist_t')
    op.drop_index(op.f('ix_enum_config_name'), table_name='enum_config')
    op.drop_table('enum_config')
    op.drop_table('comment')
    op.drop_table('class_t')
    op.drop_table('btree_t')
    op.drop_table('btree2_t')
    op.drop_table('blog_t')
    op.drop_table('auth')
    op.drop_index(op.f('ix_announcement_userid'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_title'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
