"""empty message

Revision ID: be19ba172ef3
Revises: 7138e0255705
Create Date: 2020-05-03 17:13:32.841113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be19ba172ef3'
down_revision = '7138e0255705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('attention_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('auth', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('blog_comment_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('blog_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('btree2_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('btree_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('enum_config', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('member_user_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('message_comment_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('model_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('organization', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('organization_member_relation', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('person_speech_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('project_config', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('record', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('store_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('test_child_1_to_n_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('test_child_n_n_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('test_parent_1_to_n_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('test_parent_n_n_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user_cloud_space', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user_info', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('wallet_t', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_t', 'update_time')
    op.drop_column('user_info', 'update_time')
    op.drop_column('user_cloud_space', 'update_time')
    op.drop_column('user', 'update_time')
    op.drop_column('test_parent_n_n_t', 'update_time')
    op.drop_column('test_parent_1_to_n_t', 'update_time')
    op.drop_column('test_child_n_n_t', 'update_time')
    op.drop_column('test_child_1_to_n_t', 'update_time')
    op.drop_column('store_t', 'update_time')
    op.drop_column('record', 'update_time')
    op.drop_column('project_config', 'update_time')
    op.drop_column('person_speech_t', 'update_time')
    op.drop_column('organization_member_relation', 'update_time')
    op.drop_column('organization', 'update_time')
    op.drop_column('model_t', 'update_time')
    op.drop_column('message_comment_t', 'update_time')
    op.drop_column('message', 'update_time')
    op.drop_column('member_user_t', 'update_time')
    op.drop_column('enum_config', 'update_time')
    op.drop_column('comment', 'update_time')
    op.drop_column('btree_t', 'update_time')
    op.drop_column('btree2_t', 'update_time')
    op.drop_column('blog_t', 'update_time')
    op.drop_column('blog_comment_t', 'update_time')
    op.drop_column('auth', 'update_time')
    op.drop_column('attention_t', 'update_time')
    op.drop_column('announcement', 'update_time')
    # ### end Alembic commands ###
