"""empty message

Revision ID: c2a27123aece
Revises: 9c765e86a721
Create Date: 2020-07-12 02:23:39.633104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2a27123aece'
down_revision = '9c765e86a721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StoreMemberTable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StoreMemberTable_store_id'), 'StoreMemberTable', ['store_id'], unique=False)
    op.create_index(op.f('ix_StoreMemberTable_user_id'), 'StoreMemberTable', ['user_id'], unique=False)
    op.create_table('exist_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_member_user_t_name', table_name='member_user_t')
    op.drop_index('ix_member_user_t_phone', table_name='member_user_t')
    op.drop_index('ix_member_user_t_store_id', table_name='member_user_t')
    op.drop_table('member_user_t')
    op.add_column('store_t', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_store_t_user_id'), 'store_t', ['user_id'], unique=False)
    op.add_column('wallet_t', sa.Column('money', sa.Float(), nullable=True))
    op.add_column('wallet_t', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wallet_t_store_id'), 'wallet_t', ['store_id'], unique=False)
    op.drop_column('wallet_t', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_t', sa.Column('amount', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_wallet_t_store_id'), table_name='wallet_t')
    op.drop_column('wallet_t', 'store_id')
    op.drop_column('wallet_t', 'money')
    op.drop_index(op.f('ix_store_t_user_id'), table_name='store_t')
    op.drop_column('store_t', 'user_id')
    op.create_table('member_user_t',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_member_user_t_store_id', 'member_user_t', ['store_id'], unique=False)
    op.create_index('ix_member_user_t_phone', 'member_user_t', ['phone'], unique=False)
    op.create_index('ix_member_user_t_name', 'member_user_t', ['name'], unique=False)
    op.drop_table('exist_t')
    op.drop_index(op.f('ix_StoreMemberTable_user_id'), table_name='StoreMemberTable')
    op.drop_index(op.f('ix_StoreMemberTable_store_id'), table_name='StoreMemberTable')
    op.drop_table('StoreMemberTable')
    # ### end Alembic commands ###
