"""empty message

Revision ID: c8b9b6e49dd3
Revises: 43ec4e9a8923
Create Date: 2020-04-13 00:21:05.494221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b9b6e49dd3'
down_revision = '43ec4e9a8923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attention_t', sa.Column('attentionUserId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attention_t_attentionUserId'), 'attention_t', ['attentionUserId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attention_t_attentionUserId'), table_name='attention_t')
    op.drop_column('attention_t', 'attentionUserId')
    # ### end Alembic commands ###
