"""empty message

Revision ID: ce543049389c
Revises: 83e3522ae9d1
Create Date: 2021-12-13 00:21:13.544058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce543049389c'
down_revision = '83e3522ae9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('group_code', table_name='enum_config')
    op.drop_index('group_code_2', table_name='enum_config')
    op.create_unique_constraint(None, 'enum_config', ['create_by', 'group_code', 'value'])
    op.create_unique_constraint(None, 'enum_config', ['create_by', 'group_code', 'code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.create_index('group_code_2', 'enum_config', ['group_code', 'code'], unique=True)
    op.create_index('group_code', 'enum_config', ['group_code', 'value'], unique=True)
    # ### end Alembic commands ###
