"""empty message

Revision ID: d120b3e1f1af
Revises: 33c5d895e1bc
Create Date: 2022-03-01 02:05:30.003454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd120b3e1f1af'
down_revision = '33c5d895e1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_level_vo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('create_by', sa.Integer(), nullable=True, comment='创建者id'),
    sa.Column('update_by', sa.Integer(), nullable=True, comment='修改者id'),
    sa.Column('parent_code', sa.String(length=255), server_default='-1', nullable=True, comment='父级code'),
    sa.Column('group_code', sa.String(length=255), nullable=True, comment='分组code'),
    sa.Column('code', sa.String(length=255), nullable=False, comment='枚举key值, 唯一(相当于自带路径)'),
    sa.Column('value', sa.String(length=255), nullable=False, comment='枚举value数据'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序字段'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('parent_code', 'value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_level_vo')
    # ### end Alembic commands ###
