"""empty message

Revision ID: d6806161e66c
Revises: e7f04fc3a64e
Create Date: 2022-02-22 10:03:44.486135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6806161e66c'
down_revision = 'e7f04fc3a64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_t', 'describe',
               existing_type=mysql.VARCHAR(length=256),
               comment='介绍',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goods_t', 'describe',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='介绍',
               existing_nullable=True)
    # ### end Alembic commands ###
