"""empty message

Revision ID: de9302122973
Revises: 02b6dc0d677f
Create Date: 2021-03-31 23:24:48.978645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9302122973'
down_revision = '02b6dc0d677f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_t', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_target_t_user_id'), 'target_t', ['user_id'], unique=False)
    op.create_foreign_key(None, 'target_t', 'video_user_t', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('works_t', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_works_t_user_id'), 'works_t', ['user_id'], unique=False)
    op.create_foreign_key(None, 'works_t', 'video_user_t', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works_t', type_='foreignkey')
    op.drop_index(op.f('ix_works_t_user_id'), table_name='works_t')
    op.drop_column('works_t', 'user_id')
    op.drop_constraint(None, 'target_t', type_='foreignkey')
    op.drop_index(op.f('ix_target_t_user_id'), table_name='target_t')
    op.drop_column('target_t', 'user_id')
    # ### end Alembic commands ###
