"""empty message

Revision ID: de994d170b5d
Revises: e07076eab389
Create Date: 2022-02-09 15:34:22.751186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de994d170b5d'
down_revision = 'e07076eab389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核',
               existing_nullable=True)
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;',
               existing_nullable=True)
    op.drop_column('works_t', 'state2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works_t', sa.Column('state2', mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE', 'NEXT'), nullable=True, comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;'))
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核',
               existing_comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_nullable=True)
    # ### end Alembic commands ###
