"""empty message

Revision ID: e07076eab389
Revises: 0eccd3d73d80
Create Date: 2022-02-09 15:32:50.281584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e07076eab389'
down_revision = '0eccd3d73d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核',
               existing_comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_nullable=True)
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    op.alter_column('works_t', 'state2',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE', 'NEXT'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state2',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE', 'NEXT'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;',
               existing_nullable=True)
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核; NEXT:待评审;',
               existing_comment='枚举值: APPROVE:通过; NOT_APPROVE:未通过; NONE:待审核;',
               existing_nullable=True)
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核;NEXT:待评审',
               existing_comment='枚举值: APPROVE:通过;NOT_APPROVE:未通过;NONE:待审核',
               existing_nullable=True)
    # ### end Alembic commands ###
