"""empty message

Revision ID: e1e4b249bc0b
Revises: 8fc0246b19d7
Create Date: 2022-02-09 15:03:20.541442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1e4b249bc0b'
down_revision = '8fc0246b19d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值 ReviewEnum',
               existing_nullable=True)
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值 ReviewEnum',
               existing_comment='枚举值',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment='枚举值',
               existing_comment='枚举值 ReviewEnum',
               existing_nullable=True)
    op.alter_column('target_t', 'state',
               existing_type=mysql.ENUM('APPROVE', 'NOT_APPROVE', 'NONE'),
               comment=None,
               existing_comment='枚举值 ReviewEnum',
               existing_nullable=True)
    # ### end Alembic commands ###
