"""empty message

Revision ID: e470a5a8a99e
Revises: d120b3e1f1af
Create Date: 2022-03-01 13:40:51.654947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e470a5a8a99e'
down_revision = 'd120b3e1f1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_code_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('create_by', sa.Integer(), nullable=True, comment='创建者id'),
    sa.Column('update_by', sa.Integer(), nullable=True, comment='修改者id'),
    sa.Column('url_dic', sa.JSON(), nullable=True, comment='下单桌号'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='下单桌号'),
    sa.Column('img_path', sa.String(length=255), nullable=True, comment='下单桌号'),
    sa.Column('img_width', sa.String(length=255), nullable=True, comment='下单桌号'),
    sa.Column('img_height', sa.String(length=255), nullable=True, comment='下单桌号'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_code_t')
    # ### end Alembic commands ###
