"""empty message

Revision ID: e7f04fc3a64e
Revises: 50356d19c5e6
Create Date: 2022-02-22 00:39:26.503016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7f04fc3a64e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_t', 'goods_name',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_t', 'goods_name',
               existing_type=sa.String(length=256),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
