"""empty message

Revision ID: edba4566f94a
Revises: 6e4c5c4ca5eb
Create Date: 2022-02-21 14:46:06.373855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edba4566f94a'
down_revision = '6e4c5c4ca5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcement', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('announcement', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('enum_config', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('goods_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('goods_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('log_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('log_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('order_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('order_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('store_member_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('store_member_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('store_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('store_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('story_vo', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('story_vo', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('suggest_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('suggest_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('target_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('target_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('user', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=12),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_cloud_space', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('user_role_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user_role_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('worker_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('worker_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('works_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('works_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='修改者id',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('works_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('worker_time_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('worker_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('worker_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('wallet_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user_role_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('user_role_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('user_cloud_space', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=12),
               existing_nullable=False)
    op.alter_column('user', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('user', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('target_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('target_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('suggest_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('suggest_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('story_vo', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('story_vo', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('store_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('store_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('store_member_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('store_member_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('role_permission_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('prove_vo', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('order_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('order_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('log_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('log_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('invitation_code_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('goods_t', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('goods_t', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('enum_config', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('announcement', 'update_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='修改者id',
               existing_nullable=True)
    op.alter_column('announcement', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'-1'"),
               existing_comment='创建者id',
               existing_nullable=True)
    # ### end Alembic commands ###
