"""empty message

Revision ID: f13faad5cb7d
Revises: ce543049389c
Create Date: 2021-12-23 16:53:51.106503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f13faad5cb7d'
down_revision = 'ce543049389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_t',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_t_userId'), 'log_t', ['userId'], unique=False)
    op.drop_index('create_by', table_name='enum_config')
    op.drop_index('create_by_2', table_name='enum_config')
    op.create_unique_constraint(None, 'enum_config', ['create_by', 'parent_id', 'group_code', 'value'])
    op.create_unique_constraint(None, 'enum_config', ['create_by', 'parent_id', 'group_code', 'code'])
    op.drop_column('worker_time_t', 'hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_time_t', sa.Column('hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.drop_constraint(None, 'enum_config', type_='unique')
    op.create_index('create_by_2', 'enum_config', ['create_by', 'group_code', 'code'], unique=False)
    op.create_index('create_by', 'enum_config', ['create_by', 'group_code', 'value'], unique=False)
    op.drop_index(op.f('ix_log_t_userId'), table_name='log_t')
    op.drop_table('log_t')
    # ### end Alembic commands ###
