"""empty message

Revision ID: f4f6bf4c0e53
Revises: 9ff9f22fcac8
Create Date: 2022-02-18 18:31:02.689073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4f6bf4c0e53'
down_revision = '9ff9f22fcac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default='-1',
               existing_comment='创建者id',
               existing_nullable=True)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               server_default=sa.text("''"),
               existing_nullable=True)
    op.alter_column('enum_config', 'create_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               server_default=sa.text("'SYSTEM'"),
               existing_comment='创建者id',
               existing_nullable=True)
    # ### end Alembic commands ###
