"""empty message

Revision ID: f6703ac031a4
Revises: 4fec901e39d4
Create Date: 2022-02-10 00:54:04.018642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6703ac031a4'
down_revision = '4fec901e39d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_t', 'pay',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='日薪资(元)',
               existing_comment='日薪资',
               existing_nullable=True)
    op.drop_column('worker_t', 'pay2')
    op.alter_column('worker_time_t', 'morning',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='上午工时(小时)',
               existing_comment='上午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='中午工时(小时)',
               existing_comment='中午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='下午工时(小时)',
               existing_comment='下午工时',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'night',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='晚上工时(小时)',
               existing_comment='晚上工时',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_time_t', 'night',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='晚上工时',
               existing_comment='晚上工时(小时)',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'afternoon',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='下午工时',
               existing_comment='下午工时(小时)',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'noon',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='中午工时',
               existing_comment='中午工时(小时)',
               existing_nullable=True)
    op.alter_column('worker_time_t', 'morning',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='上午工时',
               existing_comment='上午工时(小时)',
               existing_nullable=True)
    op.add_column('worker_t', sa.Column('pay2', mysql.FLOAT(precision=10, scale=2), nullable=True, comment='日薪资'))
    op.alter_column('worker_t', 'pay',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='日薪资',
               existing_comment='日薪资(元)',
               existing_nullable=True)
    # ### end Alembic commands ###
