"""empty message

Revision ID: fb7a520af96a
Revises: 104e0d54c746
Create Date: 2021-03-15 23:23:54.148582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7a520af96a'
down_revision = '104e0d54c746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('target_t_ibfk_1', 'target_t', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('target_t_ibfk_1', 'target_t', 'user', ['content'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
