# example http://nginx.org/ru/docs/example.html
# full_example https://www.nginx.cn/doc/example/fullexample.html
# docs https://www.nginx.cn/doc/index.html
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
    server {
        listen   80;
        location / {
            if ($remote_addr  ~  "159.75.92.195"){
                proxy_pass http://ip_addr_1;
                break;
            }
        }
    }

    upstream ip_addr_1 {
        server  159.75.92.195:8010 max_fails=5 fail_timeout=10;
    }

    server {
        listen   80;
        server_name ggok.top;

        location ^~ /upload_file/ {
            alias /app/world/data/;
        }

        location / {
            proxy_pass http://ggok.top:8010/;
        }
        #location ^~ /nginx/file/ {
        #       alias /app/world/data/upload_file/;
        #}
        #location ^~ /upload_file/ {
        #       root /app/world/data/;
        #}
        #location ^~ /app/world/ {
        #       alias /app/world/data/upload_file/;
        #}
        expires    -1;
    }

    server {
        listen   80;
        server_name renren.ggok.top;
        location / {
            proxy_pass http://ggok.top:8010/;
        }
    }

    server {
        listen   80;
        server_name jiangxin.ggok.top;
        location / {
            proxy_pass http://ggok.top:8020;
        }
    }

    server {
        listen   80;
        server_name tree.ggok.top;
        location / {
            proxy_pass http://ggok.top:8010/model;
        }
    }
}
