# 使用Node.js作为基础镜像
FROM node:14 AS build-stage
WORKDIR /app
# 将本地项目复制到容器的工作目录中
COPY package*.json ./
# 安装项目依赖
RUN npm install
# 复制项目的源代码
COPY . .
# 编译Vue应用
RUN npm run build

# 使用Nginx作为web服务器镜像
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
# 如果你有自定义的nginx配置文件，可以将其复制到容器中
COPY nginx.conf /etc/nginx/nginx.conf
# 暴露80端口
EXPOSE 80
# 运行nginx服务
CMD ["nginx", "-g", "daemon off;"]
# docker build -t world_web .
# docker run -d --name world_web -p 18110:80 -v /app/jingxinWeb/data/log:/var/log/nginx --restart=always world_web
